// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hotelservice.Models;

#nullable disable

namespace hotelservice.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240528102705_ScrappedHotels")]
    partial class ScrappedHotels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodPricePerPerson")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a3efaf9-b617-4289-8afc-06f4f5260106"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 83m,
                            Name = "Pinea Resort & Spa",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("ed65f816-8a45-4fdf-9460-0ba2242b4576"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 34m,
                            Name = "Diamma Resort",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("8c6d9bc2-f359-4a7b-b4de-952cf48019aa"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 31m,
                            Name = "Bonita Luxury Hotel",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("d0cdfde2-390c-42bf-9ded-14dc608b195b"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 90m,
                            Name = "Monte Carlo Vlora",
                            Street = "Rruga 28 Nentori"
                        },
                        new
                        {
                            Id = new Guid("cef41a55-9cd3-4144-ba46-c0a160dae3db"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 99m,
                            Name = "MonteCarlo Lungomare",
                            Street = "Rruga e Kavajes"
                        },
                        new
                        {
                            Id = new Guid("606eb796-f8c0-44c1-b6e7-d9c74c0e7aef"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 94m,
                            Name = "Mel Holidays",
                            Street = "Bulevardi Bajram Curri"
                        },
                        new
                        {
                            Id = new Guid("4da21b0d-26ab-4ce1-af64-a18f729b05f0"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 74m,
                            Name = "Casa Durres",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("0eca1b28-f97e-4363-b310-e9d321001a67"),
                            City = "Chania",
                            Country = "grecja",
                            FoodPricePerPerson = 91m,
                            Name = "Rethymno Mare Water Park",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("dc159078-7c6d-4b29-928b-cc635819a9d0"),
                            City = "Peloponez",
                            Country = "grecja",
                            FoodPricePerPerson = 43m,
                            Name = "Aldemar Olympian Village",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("52e2248d-8c44-413e-8f75-9194126c34cc"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 56m,
                            Name = "Studia Katerina",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("e5f235c5-c4e2-48df-a927-bc68c49f4840"),
                            City = "Heraklion",
                            Country = "grecja",
                            FoodPricePerPerson = 74m,
                            Name = "Irini Studios",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("eb92356c-007d-4038-ae7e-f140aee1a1f0"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 110m,
                            Name = "Studia Maria",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("3c876902-2e40-46ea-bbe2-700f8344aa16"),
                            City = "Olimpijska",
                            Country = "grecja",
                            FoodPricePerPerson = 31m,
                            Name = "Dias Apartments",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("99073865-f88c-4f28-8173-2193299b411a"),
                            City = "Marmaris",
                            Country = "turcja",
                            FoodPricePerPerson = 109m,
                            Name = "Turunc Resort",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("daedf97d-0277-4e8a-874f-038c0608f189"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 111m,
                            Name = "Andriake Beach Club Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("e183174a-4833-4ee0-b916-3fa404526b5a"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 114m,
                            Name = "Kimeros Park Holiday Village",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("f1c8d7e8-b08e-40c3-97e7-dcedd3520f7e"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 35m,
                            Name = "Kleopatra Micador",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("e24043be-eccc-401d-8043-7d82f6aa3655"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 50m,
                            Name = "Melissa",
                            Street = "Halaskargazi Caddesi"
                        },
                        new
                        {
                            Id = new Guid("086aec19-0d5e-4cdc-9f47-08477a6978ba"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 107m,
                            Name = "Kolibri Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("15a863c6-f0af-46cc-814f-d37a1dcef9d8"),
                            City = "Almeria",
                            Country = "hiszpania",
                            FoodPricePerPerson = 38m,
                            Name = "Evenia Zoraida Beach Resort",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("09b224f1-17f3-469f-8867-d0663c86a2ad"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 96m,
                            Name = "Evenia Olympic Park",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("b2534063-171c-4be8-93a3-4a60be8dc272"),
                            City = "Luz",
                            Country = "hiszpania",
                            FoodPricePerPerson = 94m,
                            Name = "Estival Islantilla",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("00fca576-8fd4-4ac1-97ce-8dbe8880301b"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 37m,
                            Name = "Cartago Nova by Alegria",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("d690b2bb-718a-4e7c-950a-dfbcc19e4108"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 67m,
                            Name = "Catalonia",
                            Street = "Calle de Alcalá"
                        },
                        new
                        {
                            Id = new Guid("e184f9fc-616f-406b-b2ef-6c570792a655"),
                            City = "Maresme",
                            Country = "hiszpania",
                            FoodPricePerPerson = 106m,
                            Name = "Reymar Playa",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("7c0ce2fe-9a04-426a-833b-43e8ade405be"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 77m,
                            Name = "GHT Oasis Park & Spa",
                            Street = "Gran Vía"
                        },
                        new
                        {
                            Id = new Guid("7965d57f-a0ba-408f-b4b2-c7e141df8abd"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 79m,
                            Name = "San Domenico",
                            Street = "Via del Corso"
                        },
                        new
                        {
                            Id = new Guid("22f44e2f-5cb2-4a2e-8bf4-d6b3c576f7ba"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 47m,
                            Name = "Baia di Zambrone",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("aa282794-4b9d-47c5-b7f9-4d657ecdfe4b"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 93m,
                            Name = "Rada Siri",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("1335ee5b-7ca5-4bb6-a106-f28c5a15e654"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 81m,
                            Name = "Hotel Orizzonte Blu",
                            Street = "Via Nazionale"
                        },
                        new
                        {
                            Id = new Guid("a4165ec6-43c0-4ba5-82bc-e9455e27be3f"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 116m,
                            Name = "Gradac",
                            Street = "Kapucinska ulica"
                        },
                        new
                        {
                            Id = new Guid("450f571d-b811-4a35-9b01-e88f62003758"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 31m,
                            Name = "Villa Penava",
                            Street = "Trg bana Josipa Jelačića"
                        },
                        new
                        {
                            Id = new Guid("fd2ec648-7ff4-485c-928e-c97272823862"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 42m,
                            Name = "Apartamenty Omiś",
                            Street = "Vukovarska ulica"
                        },
                        new
                        {
                            Id = new Guid("18519dfd-80db-41c4-aa75-f61803f90477"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 88m,
                            Name = "Nano",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("b729250c-f872-478b-a297-643840368782"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 83m,
                            Name = "Apartamenty Makarska",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("94c25c53-975c-452c-b35f-9112134ed5b7"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 97m,
                            Name = "Marina Resort Port Ghalib",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("c2b21d2c-9c87-4b3c-9898-76187afe18d1"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 76m,
                            Name = "Barcelo Tiran Sharm Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("8c10ea27-8d72-4d6b-ad47-98f7131e4baf"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 74m,
                            Name = "Old Vic Resort Sharm",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("e155db27-2552-4c02-8441-11626ef2bc01"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 33m,
                            Name = "Marina Lodge Port Ghalib",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("b49466bc-7701-4a23-9da8-4ea5b6bdec65"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 116m,
                            Name = "Falcon Naama Star",
                            Street = "Sharia Salah Salem"
                        },
                        new
                        {
                            Id = new Guid("aade28ca-437f-48cb-aee9-99a510b740e6"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 80m,
                            Name = "Protels Crystal Beach Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("b90c2fe3-4d24-4bcd-aa95-9659c1b5857e"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 89m,
                            Name = "MG Alexander The Great",
                            Street = "Sharia Gamal Abdel Nasser"
                        },
                        new
                        {
                            Id = new Guid("73b1ede0-a09e-42e5-8709-49982716aa64"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 83m,
                            Name = "Bliss Nada Beach Resort",
                            Street = "Sharia Tahrir"
                        });
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("218d1fe6-fb23-4173-91c6-a2a7da0b0c8b"),
                            Count = 3,
                            HotelId = new Guid("0a3efaf9-b617-4289-8afc-06f4f5260106"),
                            Price = 119m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("72095243-4828-4f2b-a6c2-f4d1aae50ea8"),
                            Count = 2,
                            HotelId = new Guid("0a3efaf9-b617-4289-8afc-06f4f5260106"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("483cc984-d591-42dd-9a34-73e517b1db6f"),
                            Count = 2,
                            HotelId = new Guid("0a3efaf9-b617-4289-8afc-06f4f5260106"),
                            Price = 123m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4453fd93-a28d-4c82-a6e4-1ea528376826"),
                            Count = 2,
                            HotelId = new Guid("0a3efaf9-b617-4289-8afc-06f4f5260106"),
                            Price = 215m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2444778b-9f4a-4aad-95ad-605df060d730"),
                            Count = 2,
                            HotelId = new Guid("ed65f816-8a45-4fdf-9460-0ba2242b4576"),
                            Price = 145m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2cfc7807-4801-4a39-a511-f66e8a1aec34"),
                            Count = 2,
                            HotelId = new Guid("ed65f816-8a45-4fdf-9460-0ba2242b4576"),
                            Price = 138m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c2c9a531-17de-448a-b8b6-04a718489495"),
                            Count = 3,
                            HotelId = new Guid("ed65f816-8a45-4fdf-9460-0ba2242b4576"),
                            Price = 74m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("70d4aaac-a563-44c5-b18d-865d36397a66"),
                            Count = 1,
                            HotelId = new Guid("ed65f816-8a45-4fdf-9460-0ba2242b4576"),
                            Price = 205m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6bc53aa9-2c9a-4b32-bd21-5ca0fbe5def8"),
                            Count = 2,
                            HotelId = new Guid("8c6d9bc2-f359-4a7b-b4de-952cf48019aa"),
                            Price = 186m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("480c9dbd-86b9-429f-94e1-1e298850fb3a"),
                            Count = 3,
                            HotelId = new Guid("8c6d9bc2-f359-4a7b-b4de-952cf48019aa"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("63239170-e0b9-4b83-8353-388e7c243fc9"),
                            Count = 1,
                            HotelId = new Guid("8c6d9bc2-f359-4a7b-b4de-952cf48019aa"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2b58ba91-d477-4360-8034-7fba74171031"),
                            Count = 1,
                            HotelId = new Guid("8c6d9bc2-f359-4a7b-b4de-952cf48019aa"),
                            Price = 69m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b53dad0a-1c73-44dc-839e-07ff6ea951f6"),
                            Count = 1,
                            HotelId = new Guid("d0cdfde2-390c-42bf-9ded-14dc608b195b"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("55aee54e-c00d-42b5-979f-e2c87f7f4e44"),
                            Count = 3,
                            HotelId = new Guid("d0cdfde2-390c-42bf-9ded-14dc608b195b"),
                            Price = 147m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bde342a2-4964-4d34-92a6-d74b4ee1af79"),
                            Count = 2,
                            HotelId = new Guid("d0cdfde2-390c-42bf-9ded-14dc608b195b"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7be6ea95-e61b-42ef-9807-280eff6be55d"),
                            Count = 3,
                            HotelId = new Guid("d0cdfde2-390c-42bf-9ded-14dc608b195b"),
                            Price = 110m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("63fcc672-a4ce-4218-a3f3-e4c133b8ed01"),
                            Count = 3,
                            HotelId = new Guid("cef41a55-9cd3-4144-ba46-c0a160dae3db"),
                            Price = 193m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1accea07-829f-46d8-93aa-223fc4aa6c15"),
                            Count = 1,
                            HotelId = new Guid("cef41a55-9cd3-4144-ba46-c0a160dae3db"),
                            Price = 182m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3b7221db-e30a-4eeb-b7e8-59960655ca31"),
                            Count = 1,
                            HotelId = new Guid("cef41a55-9cd3-4144-ba46-c0a160dae3db"),
                            Price = 238m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("336e3c8b-328b-49ca-9372-02cf82bfefef"),
                            Count = 3,
                            HotelId = new Guid("cef41a55-9cd3-4144-ba46-c0a160dae3db"),
                            Price = 70m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b53d315e-aaaa-4912-8ced-6b466c54a299"),
                            Count = 3,
                            HotelId = new Guid("606eb796-f8c0-44c1-b6e7-d9c74c0e7aef"),
                            Price = 219m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1d56fae4-bc92-4b05-a7b2-b8d7b2404a86"),
                            Count = 3,
                            HotelId = new Guid("606eb796-f8c0-44c1-b6e7-d9c74c0e7aef"),
                            Price = 109m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4d4b78c7-420e-459b-af3e-638a5013e9e7"),
                            Count = 3,
                            HotelId = new Guid("606eb796-f8c0-44c1-b6e7-d9c74c0e7aef"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("19887486-63c8-4c8c-805b-0161026559ff"),
                            Count = 2,
                            HotelId = new Guid("606eb796-f8c0-44c1-b6e7-d9c74c0e7aef"),
                            Price = 143m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("afc4608f-8615-4974-bd2f-048e9d64964f"),
                            Count = 3,
                            HotelId = new Guid("4da21b0d-26ab-4ce1-af64-a18f729b05f0"),
                            Price = 104m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d7bb40af-0060-4083-8a49-38eca125d088"),
                            Count = 1,
                            HotelId = new Guid("4da21b0d-26ab-4ce1-af64-a18f729b05f0"),
                            Price = 136m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("99cd4b93-95f5-4845-8c1b-e0bac1ba03c6"),
                            Count = 3,
                            HotelId = new Guid("4da21b0d-26ab-4ce1-af64-a18f729b05f0"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ad9b801b-84c8-42ad-9b45-44c46c07602a"),
                            Count = 2,
                            HotelId = new Guid("4da21b0d-26ab-4ce1-af64-a18f729b05f0"),
                            Price = 105m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("49d218c0-5b0d-4308-8781-c9c762131aa0"),
                            Count = 2,
                            HotelId = new Guid("0eca1b28-f97e-4363-b310-e9d321001a67"),
                            Price = 211m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("85f64acb-f3ae-4666-b8e0-255121d366ef"),
                            Count = 1,
                            HotelId = new Guid("0eca1b28-f97e-4363-b310-e9d321001a67"),
                            Price = 77m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("66e13e21-851c-46ba-8363-01e11bb8f9ae"),
                            Count = 2,
                            HotelId = new Guid("0eca1b28-f97e-4363-b310-e9d321001a67"),
                            Price = 169m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ce2e107a-7e37-4121-8724-ff7b879065c6"),
                            Count = 1,
                            HotelId = new Guid("0eca1b28-f97e-4363-b310-e9d321001a67"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ba0313a1-27e3-426b-800e-378fdd85e854"),
                            Count = 2,
                            HotelId = new Guid("dc159078-7c6d-4b29-928b-cc635819a9d0"),
                            Price = 239m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2599221b-c375-4a44-b926-95351c9d9053"),
                            Count = 3,
                            HotelId = new Guid("dc159078-7c6d-4b29-928b-cc635819a9d0"),
                            Price = 208m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ddf0d252-552c-40bc-81db-b12a1bd0fb94"),
                            Count = 3,
                            HotelId = new Guid("dc159078-7c6d-4b29-928b-cc635819a9d0"),
                            Price = 161m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4156a32b-a715-4454-bc4d-83a818534f9d"),
                            Count = 1,
                            HotelId = new Guid("dc159078-7c6d-4b29-928b-cc635819a9d0"),
                            Price = 64m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5137c90a-f581-4c63-9728-690efa62c17e"),
                            Count = 1,
                            HotelId = new Guid("52e2248d-8c44-413e-8f75-9194126c34cc"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3980fabf-808d-444d-b4f8-772468ce6fc9"),
                            Count = 2,
                            HotelId = new Guid("52e2248d-8c44-413e-8f75-9194126c34cc"),
                            Price = 234m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("27806582-a4fe-498c-a091-5d4669669794"),
                            Count = 3,
                            HotelId = new Guid("52e2248d-8c44-413e-8f75-9194126c34cc"),
                            Price = 84m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("cb05be9d-d4f4-45bd-9818-4dfb31144d67"),
                            Count = 3,
                            HotelId = new Guid("52e2248d-8c44-413e-8f75-9194126c34cc"),
                            Price = 216m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("55310490-d52c-4150-8f6f-eee4a5fb1e28"),
                            Count = 2,
                            HotelId = new Guid("e5f235c5-c4e2-48df-a927-bc68c49f4840"),
                            Price = 165m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9ad7322e-ec58-43fc-b0a2-d8c0e377f0dd"),
                            Count = 2,
                            HotelId = new Guid("e5f235c5-c4e2-48df-a927-bc68c49f4840"),
                            Price = 88m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("80666e6f-ad58-451c-831c-c12305c8b56e"),
                            Count = 1,
                            HotelId = new Guid("e5f235c5-c4e2-48df-a927-bc68c49f4840"),
                            Price = 210m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("49fc83d9-9317-4de0-903f-3ad956786453"),
                            Count = 1,
                            HotelId = new Guid("e5f235c5-c4e2-48df-a927-bc68c49f4840"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ee01e133-8f08-4410-8ac8-ebf4830ada27"),
                            Count = 1,
                            HotelId = new Guid("eb92356c-007d-4038-ae7e-f140aee1a1f0"),
                            Price = 130m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e918dbff-78a1-430e-bb0a-a9f4ae3fc15a"),
                            Count = 3,
                            HotelId = new Guid("eb92356c-007d-4038-ae7e-f140aee1a1f0"),
                            Price = 97m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("815a0e39-831c-4bb8-b322-6b6ba3628468"),
                            Count = 3,
                            HotelId = new Guid("eb92356c-007d-4038-ae7e-f140aee1a1f0"),
                            Price = 165m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9bb66b6c-d95d-4ad1-ba45-f20db3da2740"),
                            Count = 1,
                            HotelId = new Guid("eb92356c-007d-4038-ae7e-f140aee1a1f0"),
                            Price = 72m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2010ff59-a091-4cb2-920f-635bfb84c3eb"),
                            Count = 1,
                            HotelId = new Guid("3c876902-2e40-46ea-bbe2-700f8344aa16"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dae716c4-19e5-4ae5-afc2-92fc91ce810b"),
                            Count = 2,
                            HotelId = new Guid("3c876902-2e40-46ea-bbe2-700f8344aa16"),
                            Price = 125m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("299f9ec5-81a1-4e66-b319-b755f4a3ddeb"),
                            Count = 1,
                            HotelId = new Guid("3c876902-2e40-46ea-bbe2-700f8344aa16"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9adf5a6a-321f-467f-987a-514b9d4635fd"),
                            Count = 1,
                            HotelId = new Guid("3c876902-2e40-46ea-bbe2-700f8344aa16"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4e45b01e-294a-4c90-ae45-63aee3d8279f"),
                            Count = 2,
                            HotelId = new Guid("99073865-f88c-4f28-8173-2193299b411a"),
                            Price = 207m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ca013163-412c-4397-af1d-b680a8cc4cf6"),
                            Count = 3,
                            HotelId = new Guid("99073865-f88c-4f28-8173-2193299b411a"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6aa4194b-426d-482e-a0ef-e3169f34acd2"),
                            Count = 3,
                            HotelId = new Guid("99073865-f88c-4f28-8173-2193299b411a"),
                            Price = 146m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("688591ed-6b32-473a-b1e3-58ff36c778b9"),
                            Count = 1,
                            HotelId = new Guid("99073865-f88c-4f28-8173-2193299b411a"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1d8506e5-56c4-428c-94e7-f16c79942c6d"),
                            Count = 3,
                            HotelId = new Guid("daedf97d-0277-4e8a-874f-038c0608f189"),
                            Price = 132m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("6c01386b-05cc-4da9-a01b-015daecd3c23"),
                            Count = 2,
                            HotelId = new Guid("daedf97d-0277-4e8a-874f-038c0608f189"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6d48e5d6-b6e2-484f-af4a-18785ea976b0"),
                            Count = 1,
                            HotelId = new Guid("daedf97d-0277-4e8a-874f-038c0608f189"),
                            Price = 243m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("5bb7c355-aacc-4722-99cc-93a51f2b56f4"),
                            Count = 2,
                            HotelId = new Guid("daedf97d-0277-4e8a-874f-038c0608f189"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("743b84c0-9625-4cb9-8643-6a4c6ea90534"),
                            Count = 3,
                            HotelId = new Guid("e183174a-4833-4ee0-b916-3fa404526b5a"),
                            Price = 148m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1c787a55-971e-4f83-aabf-de655f43bdf8"),
                            Count = 2,
                            HotelId = new Guid("e183174a-4833-4ee0-b916-3fa404526b5a"),
                            Price = 168m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bb063a09-9326-482d-a095-bb5c1dd14551"),
                            Count = 3,
                            HotelId = new Guid("e183174a-4833-4ee0-b916-3fa404526b5a"),
                            Price = 230m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("3b2277b7-ec06-4710-9523-520813b73bfc"),
                            Count = 3,
                            HotelId = new Guid("e183174a-4833-4ee0-b916-3fa404526b5a"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("51803451-e86b-4b63-9644-627b5903d423"),
                            Count = 1,
                            HotelId = new Guid("f1c8d7e8-b08e-40c3-97e7-dcedd3520f7e"),
                            Price = 201m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("7627832c-a64b-47b9-bea7-b921eb8c519b"),
                            Count = 2,
                            HotelId = new Guid("f1c8d7e8-b08e-40c3-97e7-dcedd3520f7e"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d11cc252-5fc9-4ae0-8302-aec3038c8e02"),
                            Count = 2,
                            HotelId = new Guid("f1c8d7e8-b08e-40c3-97e7-dcedd3520f7e"),
                            Price = 76m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("93da5343-6328-452c-b716-c1829713ca5d"),
                            Count = 1,
                            HotelId = new Guid("f1c8d7e8-b08e-40c3-97e7-dcedd3520f7e"),
                            Price = 63m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("71efcb4d-c10c-44c9-bf41-51cbfee53e8d"),
                            Count = 1,
                            HotelId = new Guid("e24043be-eccc-401d-8043-7d82f6aa3655"),
                            Price = 175m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e3c5f804-618b-45bc-9821-ab5d1d8d56ce"),
                            Count = 1,
                            HotelId = new Guid("e24043be-eccc-401d-8043-7d82f6aa3655"),
                            Price = 245m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ee1a5b1b-14fa-4a53-b1b1-3ce901a2ef53"),
                            Count = 1,
                            HotelId = new Guid("e24043be-eccc-401d-8043-7d82f6aa3655"),
                            Price = 50m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("74c2b12e-aaa0-4acc-beac-9da94136ba0a"),
                            Count = 1,
                            HotelId = new Guid("e24043be-eccc-401d-8043-7d82f6aa3655"),
                            Price = 219m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6ce3a6ce-8fed-4253-a914-e757751d855b"),
                            Count = 3,
                            HotelId = new Guid("086aec19-0d5e-4cdc-9f47-08477a6978ba"),
                            Price = 215m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3efc743b-1a3a-49ff-bc48-56974496f3c8"),
                            Count = 1,
                            HotelId = new Guid("086aec19-0d5e-4cdc-9f47-08477a6978ba"),
                            Price = 164m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("33406056-5a39-414f-93d0-3c694949b08d"),
                            Count = 3,
                            HotelId = new Guid("086aec19-0d5e-4cdc-9f47-08477a6978ba"),
                            Price = 163m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d00689b2-b79b-4d9e-89bb-85ff9f76a9d3"),
                            Count = 2,
                            HotelId = new Guid("086aec19-0d5e-4cdc-9f47-08477a6978ba"),
                            Price = 247m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4952773c-1fa5-4913-b312-077db9651e6b"),
                            Count = 1,
                            HotelId = new Guid("15a863c6-f0af-46cc-814f-d37a1dcef9d8"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d55296c8-83fc-4c4f-a874-de40379dbcbf"),
                            Count = 3,
                            HotelId = new Guid("15a863c6-f0af-46cc-814f-d37a1dcef9d8"),
                            Price = 149m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2548a1f6-408c-4f2a-abc5-2f9b6d0357fc"),
                            Count = 3,
                            HotelId = new Guid("15a863c6-f0af-46cc-814f-d37a1dcef9d8"),
                            Price = 197m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("97fb4e24-dd16-4166-9c1a-e9c9749eaf33"),
                            Count = 2,
                            HotelId = new Guid("15a863c6-f0af-46cc-814f-d37a1dcef9d8"),
                            Price = 237m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f4f7a2b2-bbce-4446-8fda-75097c17720f"),
                            Count = 2,
                            HotelId = new Guid("09b224f1-17f3-469f-8867-d0663c86a2ad"),
                            Price = 87m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("6953fa73-d4cb-4b19-8bbc-0e46ad7563e2"),
                            Count = 1,
                            HotelId = new Guid("09b224f1-17f3-469f-8867-d0663c86a2ad"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d4a43b75-74c3-404e-990b-563f4ed77a99"),
                            Count = 3,
                            HotelId = new Guid("09b224f1-17f3-469f-8867-d0663c86a2ad"),
                            Price = 70m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("8a691dc3-b59d-4ae3-92b5-d7b23c2322d3"),
                            Count = 3,
                            HotelId = new Guid("09b224f1-17f3-469f-8867-d0663c86a2ad"),
                            Price = 184m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2d1b62be-c8a5-44cf-b173-e990068f4d99"),
                            Count = 3,
                            HotelId = new Guid("b2534063-171c-4be8-93a3-4a60be8dc272"),
                            Price = 242m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("def96cdb-c68d-4189-bee5-fc5134625645"),
                            Count = 1,
                            HotelId = new Guid("b2534063-171c-4be8-93a3-4a60be8dc272"),
                            Price = 132m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("9a31fed0-d5d3-49d0-a6dd-65e22a443aa4"),
                            Count = 3,
                            HotelId = new Guid("b2534063-171c-4be8-93a3-4a60be8dc272"),
                            Price = 142m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4a60fe73-b213-445d-9a24-225973b9453a"),
                            Count = 2,
                            HotelId = new Guid("b2534063-171c-4be8-93a3-4a60be8dc272"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4652781c-62ec-4c3f-b9c4-cef2d952fad7"),
                            Count = 3,
                            HotelId = new Guid("00fca576-8fd4-4ac1-97ce-8dbe8880301b"),
                            Price = 233m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8c38e2c7-09e7-4a15-b792-ab68fff47fde"),
                            Count = 3,
                            HotelId = new Guid("00fca576-8fd4-4ac1-97ce-8dbe8880301b"),
                            Price = 204m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("5776eb4f-1350-481d-b311-6b15459fac44"),
                            Count = 1,
                            HotelId = new Guid("00fca576-8fd4-4ac1-97ce-8dbe8880301b"),
                            Price = 171m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("31786618-681a-48a0-84a5-76dd9b1bf97b"),
                            Count = 1,
                            HotelId = new Guid("00fca576-8fd4-4ac1-97ce-8dbe8880301b"),
                            Price = 94m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ef7418e2-3165-41b8-9a6d-900b7b0c2dd6"),
                            Count = 1,
                            HotelId = new Guid("d690b2bb-718a-4e7c-950a-dfbcc19e4108"),
                            Price = 53m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("56c9253b-e6ba-43ea-9b74-478c025c4ea7"),
                            Count = 3,
                            HotelId = new Guid("d690b2bb-718a-4e7c-950a-dfbcc19e4108"),
                            Price = 92m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3c4c5bfb-0546-41d9-ad0a-313101da05ef"),
                            Count = 3,
                            HotelId = new Guid("d690b2bb-718a-4e7c-950a-dfbcc19e4108"),
                            Price = 250m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ec004b7c-8d3d-4967-b6b1-636ee3b72e81"),
                            Count = 3,
                            HotelId = new Guid("d690b2bb-718a-4e7c-950a-dfbcc19e4108"),
                            Price = 241m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c53cdec2-302f-44a1-b06a-0ea2d36ca9e0"),
                            Count = 3,
                            HotelId = new Guid("e184f9fc-616f-406b-b2ef-6c570792a655"),
                            Price = 190m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1a53f593-e2f5-41c6-af7e-a54e539a49ab"),
                            Count = 1,
                            HotelId = new Guid("e184f9fc-616f-406b-b2ef-6c570792a655"),
                            Price = 112m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("44532019-8fff-46cb-b48c-a6422a8485cd"),
                            Count = 2,
                            HotelId = new Guid("e184f9fc-616f-406b-b2ef-6c570792a655"),
                            Price = 152m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("283a6834-96d1-4b6a-9a86-64c914358be9"),
                            Count = 1,
                            HotelId = new Guid("e184f9fc-616f-406b-b2ef-6c570792a655"),
                            Price = 177m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3362c175-627a-4cf1-b536-5f2f95ee725e"),
                            Count = 2,
                            HotelId = new Guid("7c0ce2fe-9a04-426a-833b-43e8ade405be"),
                            Price = 60m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c1695ca9-9d49-4a22-b74e-8684d5c6e36e"),
                            Count = 3,
                            HotelId = new Guid("7c0ce2fe-9a04-426a-833b-43e8ade405be"),
                            Price = 190m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("85c3454a-b83d-4878-88e1-5b987d27ba1e"),
                            Count = 3,
                            HotelId = new Guid("7c0ce2fe-9a04-426a-833b-43e8ade405be"),
                            Price = 77m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6d3312da-95bd-4b00-b33b-c1a907a4d4d0"),
                            Count = 3,
                            HotelId = new Guid("7c0ce2fe-9a04-426a-833b-43e8ade405be"),
                            Price = 217m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c9d5c9fb-3eb8-459a-a00b-280aeefbdc69"),
                            Count = 1,
                            HotelId = new Guid("7965d57f-a0ba-408f-b4b2-c7e141df8abd"),
                            Price = 146m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dee509a7-73ec-4a99-b931-cf140f6304b5"),
                            Count = 3,
                            HotelId = new Guid("7965d57f-a0ba-408f-b4b2-c7e141df8abd"),
                            Price = 107m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("caaa157b-1a50-43dd-aaac-9274f0fcab4b"),
                            Count = 1,
                            HotelId = new Guid("7965d57f-a0ba-408f-b4b2-c7e141df8abd"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("633c2ce6-ce29-4802-b785-82e91ee59243"),
                            Count = 3,
                            HotelId = new Guid("7965d57f-a0ba-408f-b4b2-c7e141df8abd"),
                            Price = 162m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c448be82-ef4e-48fb-8d2f-56e5d09a0eab"),
                            Count = 2,
                            HotelId = new Guid("22f44e2f-5cb2-4a2e-8bf4-d6b3c576f7ba"),
                            Price = 213m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("bd800ee4-5641-42ae-9a0b-6041f5ad720f"),
                            Count = 2,
                            HotelId = new Guid("22f44e2f-5cb2-4a2e-8bf4-d6b3c576f7ba"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("313be7dc-e62f-41d7-9528-6005f077646b"),
                            Count = 2,
                            HotelId = new Guid("22f44e2f-5cb2-4a2e-8bf4-d6b3c576f7ba"),
                            Price = 140m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1ace775f-e083-462e-8b4b-6d12499285c5"),
                            Count = 2,
                            HotelId = new Guid("22f44e2f-5cb2-4a2e-8bf4-d6b3c576f7ba"),
                            Price = 250m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("01c8f7d4-5191-44ec-b944-acea3831a540"),
                            Count = 3,
                            HotelId = new Guid("aa282794-4b9d-47c5-b7f9-4d657ecdfe4b"),
                            Price = 178m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("63bc813d-207f-41d6-8431-5aa191ef3ea4"),
                            Count = 3,
                            HotelId = new Guid("aa282794-4b9d-47c5-b7f9-4d657ecdfe4b"),
                            Price = 216m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("64fd57a0-801a-42d4-97ee-e8a19a9f6798"),
                            Count = 1,
                            HotelId = new Guid("aa282794-4b9d-47c5-b7f9-4d657ecdfe4b"),
                            Price = 98m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b97786d5-f052-42e9-9bc7-d4014279ce5a"),
                            Count = 3,
                            HotelId = new Guid("aa282794-4b9d-47c5-b7f9-4d657ecdfe4b"),
                            Price = 165m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("29cf8d8d-a13b-412e-90b1-f9eab17c08b3"),
                            Count = 3,
                            HotelId = new Guid("1335ee5b-7ca5-4bb6-a106-f28c5a15e654"),
                            Price = 118m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4161eab2-4d2f-4dd0-a53b-ed4b1f6419e1"),
                            Count = 2,
                            HotelId = new Guid("1335ee5b-7ca5-4bb6-a106-f28c5a15e654"),
                            Price = 73m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a4ac1750-509f-4f8c-862e-748f80f0695e"),
                            Count = 1,
                            HotelId = new Guid("1335ee5b-7ca5-4bb6-a106-f28c5a15e654"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("0960b91d-1b61-460e-9dcb-ad9e36909c5a"),
                            Count = 2,
                            HotelId = new Guid("1335ee5b-7ca5-4bb6-a106-f28c5a15e654"),
                            Price = 81m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f1782a56-c79f-4ff2-8b8b-bb681f639b38"),
                            Count = 2,
                            HotelId = new Guid("a4165ec6-43c0-4ba5-82bc-e9455e27be3f"),
                            Price = 111m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("6eb52e44-5c8e-43c5-8040-08d8f3a81b51"),
                            Count = 1,
                            HotelId = new Guid("a4165ec6-43c0-4ba5-82bc-e9455e27be3f"),
                            Price = 110m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("85b06894-8cab-475c-94fb-b6797891b8d5"),
                            Count = 1,
                            HotelId = new Guid("a4165ec6-43c0-4ba5-82bc-e9455e27be3f"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4a0a21a2-65a7-409b-9f4a-049440f0f379"),
                            Count = 3,
                            HotelId = new Guid("a4165ec6-43c0-4ba5-82bc-e9455e27be3f"),
                            Price = 239m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3f633072-9c83-4511-bd6b-3fdd6d0bac78"),
                            Count = 1,
                            HotelId = new Guid("450f571d-b811-4a35-9b01-e88f62003758"),
                            Price = 121m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("7e5dc0ba-d394-4117-9e5a-af22f67334b6"),
                            Count = 1,
                            HotelId = new Guid("450f571d-b811-4a35-9b01-e88f62003758"),
                            Price = 187m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("503bd43c-1489-4515-9e19-b9227ef5065e"),
                            Count = 2,
                            HotelId = new Guid("450f571d-b811-4a35-9b01-e88f62003758"),
                            Price = 201m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("bc74a4fb-2bdc-4b08-89c7-62c993561d7c"),
                            Count = 1,
                            HotelId = new Guid("450f571d-b811-4a35-9b01-e88f62003758"),
                            Price = 73m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f54c4ea1-a447-47a8-a821-e9d758012b00"),
                            Count = 3,
                            HotelId = new Guid("fd2ec648-7ff4-485c-928e-c97272823862"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fc88df53-0235-4497-8ec2-8c9503ad9cc8"),
                            Count = 1,
                            HotelId = new Guid("fd2ec648-7ff4-485c-928e-c97272823862"),
                            Price = 145m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b94a2dc4-69cc-420a-89f2-a2555ae515ee"),
                            Count = 2,
                            HotelId = new Guid("fd2ec648-7ff4-485c-928e-c97272823862"),
                            Price = 221m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d57b19b7-17e2-4122-b4d1-8681bc163897"),
                            Count = 2,
                            HotelId = new Guid("fd2ec648-7ff4-485c-928e-c97272823862"),
                            Price = 108m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("90033f73-589b-4218-8230-c31a9b8b4944"),
                            Count = 2,
                            HotelId = new Guid("18519dfd-80db-41c4-aa75-f61803f90477"),
                            Price = 220m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3ade7f47-f02e-4c23-a1ff-33dab1d76755"),
                            Count = 2,
                            HotelId = new Guid("18519dfd-80db-41c4-aa75-f61803f90477"),
                            Price = 96m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("09b8175f-7499-457c-b02e-851feb668414"),
                            Count = 1,
                            HotelId = new Guid("18519dfd-80db-41c4-aa75-f61803f90477"),
                            Price = 143m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f2f7b3a2-49cc-406a-adde-5e874cc49365"),
                            Count = 3,
                            HotelId = new Guid("18519dfd-80db-41c4-aa75-f61803f90477"),
                            Price = 71m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2749ae1f-ccfe-4d91-9eda-6dade48a8c3e"),
                            Count = 2,
                            HotelId = new Guid("b729250c-f872-478b-a297-643840368782"),
                            Price = 179m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("262b3c05-d7e1-4618-9486-0ab22c93a48a"),
                            Count = 3,
                            HotelId = new Guid("b729250c-f872-478b-a297-643840368782"),
                            Price = 155m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("18890b13-ffb7-4890-a554-751153d38013"),
                            Count = 1,
                            HotelId = new Guid("b729250c-f872-478b-a297-643840368782"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("587d726a-5017-415d-a354-f2069bcf2095"),
                            Count = 1,
                            HotelId = new Guid("b729250c-f872-478b-a297-643840368782"),
                            Price = 195m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("fa1a3a04-c1d4-49be-8fe2-82c7d816b154"),
                            Count = 2,
                            HotelId = new Guid("94c25c53-975c-452c-b35f-9112134ed5b7"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("48090581-34c4-43fe-ba64-cfddf741607e"),
                            Count = 3,
                            HotelId = new Guid("94c25c53-975c-452c-b35f-9112134ed5b7"),
                            Price = 195m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("52608c29-31fd-40f1-8ba9-0bc124666a14"),
                            Count = 3,
                            HotelId = new Guid("94c25c53-975c-452c-b35f-9112134ed5b7"),
                            Price = 180m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("8b59680e-8ac6-4fb1-85a8-9ae192a6c8ab"),
                            Count = 3,
                            HotelId = new Guid("94c25c53-975c-452c-b35f-9112134ed5b7"),
                            Price = 210m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7049255f-78cb-42dc-9142-b3077cc5535d"),
                            Count = 2,
                            HotelId = new Guid("c2b21d2c-9c87-4b3c-9898-76187afe18d1"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d8643756-09d1-44d5-8d5c-6b0aab0d13ee"),
                            Count = 2,
                            HotelId = new Guid("c2b21d2c-9c87-4b3c-9898-76187afe18d1"),
                            Price = 221m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("130c46ad-159c-4012-b8f3-ae5654f90ad2"),
                            Count = 3,
                            HotelId = new Guid("c2b21d2c-9c87-4b3c-9898-76187afe18d1"),
                            Price = 223m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b3d865d0-e72f-43b1-aba4-590f19dcc29b"),
                            Count = 3,
                            HotelId = new Guid("c2b21d2c-9c87-4b3c-9898-76187afe18d1"),
                            Price = 135m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c2bee144-ea6b-4d3c-b4bc-2d10f354a461"),
                            Count = 2,
                            HotelId = new Guid("8c10ea27-8d72-4d6b-ad47-98f7131e4baf"),
                            Price = 66m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dcf195da-a585-42da-bd79-13e455ca9388"),
                            Count = 2,
                            HotelId = new Guid("8c10ea27-8d72-4d6b-ad47-98f7131e4baf"),
                            Price = 179m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6e28b834-ce20-4254-bffc-085fa27e197c"),
                            Count = 2,
                            HotelId = new Guid("8c10ea27-8d72-4d6b-ad47-98f7131e4baf"),
                            Price = 125m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ce1eeed5-a141-48fc-8618-aedef998412c"),
                            Count = 2,
                            HotelId = new Guid("8c10ea27-8d72-4d6b-ad47-98f7131e4baf"),
                            Price = 147m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9d7db273-ec5f-45af-a1c2-b55e71378ff8"),
                            Count = 2,
                            HotelId = new Guid("e155db27-2552-4c02-8441-11626ef2bc01"),
                            Price = 176m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("7bcf531b-c980-4fcd-bfad-d24a73f2cb52"),
                            Count = 3,
                            HotelId = new Guid("e155db27-2552-4c02-8441-11626ef2bc01"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("74703dc7-f077-4d0d-85f1-10defa129717"),
                            Count = 3,
                            HotelId = new Guid("e155db27-2552-4c02-8441-11626ef2bc01"),
                            Price = 127m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7f79f219-2e20-43a8-9e04-9975b2e48916"),
                            Count = 3,
                            HotelId = new Guid("e155db27-2552-4c02-8441-11626ef2bc01"),
                            Price = 88m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("80b460a3-0b74-4bcf-84c8-8f4fe3757795"),
                            Count = 1,
                            HotelId = new Guid("b49466bc-7701-4a23-9da8-4ea5b6bdec65"),
                            Price = 158m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e9f5e5d3-612b-46ad-a883-878fdae3d2bc"),
                            Count = 2,
                            HotelId = new Guid("b49466bc-7701-4a23-9da8-4ea5b6bdec65"),
                            Price = 133m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a481e6ac-7bbd-47ce-bb64-81dc576b4059"),
                            Count = 3,
                            HotelId = new Guid("b49466bc-7701-4a23-9da8-4ea5b6bdec65"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d1b0053a-e39c-4611-8a0d-87f0a72297b9"),
                            Count = 3,
                            HotelId = new Guid("b49466bc-7701-4a23-9da8-4ea5b6bdec65"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("27d213e5-8a69-4099-bded-9e8fad5c1da0"),
                            Count = 3,
                            HotelId = new Guid("aade28ca-437f-48cb-aee9-99a510b740e6"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("01b563b3-b5f0-4c2d-9393-279e7e1d0ce0"),
                            Count = 2,
                            HotelId = new Guid("aade28ca-437f-48cb-aee9-99a510b740e6"),
                            Price = 62m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("590f4889-a519-489b-9927-b757916d360b"),
                            Count = 2,
                            HotelId = new Guid("aade28ca-437f-48cb-aee9-99a510b740e6"),
                            Price = 162m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9ae5045e-59e5-4677-9134-733f9e2b156e"),
                            Count = 3,
                            HotelId = new Guid("aade28ca-437f-48cb-aee9-99a510b740e6"),
                            Price = 191m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("96295dec-3a0b-48e7-aab7-2068c5d5c7be"),
                            Count = 2,
                            HotelId = new Guid("b90c2fe3-4d24-4bcd-aa95-9659c1b5857e"),
                            Price = 188m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d7466e53-b7a2-45d5-bf69-07a646afb84e"),
                            Count = 2,
                            HotelId = new Guid("b90c2fe3-4d24-4bcd-aa95-9659c1b5857e"),
                            Price = 90m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f30a1940-3f84-472f-bee7-e8efba10650a"),
                            Count = 2,
                            HotelId = new Guid("b90c2fe3-4d24-4bcd-aa95-9659c1b5857e"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d64e249e-d3bd-41d8-9586-e048164c1f3c"),
                            Count = 2,
                            HotelId = new Guid("b90c2fe3-4d24-4bcd-aa95-9659c1b5857e"),
                            Price = 209m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("78483eb7-6f0d-481b-be0c-bcce637ed81d"),
                            Count = 1,
                            HotelId = new Guid("73b1ede0-a09e-42e5-8709-49982716aa64"),
                            Price = 123m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4a3813e2-1b63-4666-ad67-decbbb4c2c7c"),
                            Count = 1,
                            HotelId = new Guid("73b1ede0-a09e-42e5-8709-49982716aa64"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("609fbfed-b202-48bb-8081-db34fefd0780"),
                            Count = 1,
                            HotelId = new Guid("73b1ede0-a09e-42e5-8709-49982716aa64"),
                            Price = 218m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("87b28a08-64c9-48fc-8dc8-089b40879738"),
                            Count = 1,
                            HotelId = new Guid("73b1ede0-a09e-42e5-8709-49982716aa64"),
                            Price = 235m,
                            Size = 5
                        });
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomsReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Discounts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.HasOne("hotelservice.Models.Room", null)
                        .WithMany("Bookings")
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
