// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hotelservice.Models;

#nullable disable

namespace hotelservice.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240609120159_AddPopularHotels")]
    partial class AddPopularHotels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodPricePerPerson")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccfd895c-3aea-4394-a6eb-a4527b204cec"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 83m,
                            Name = "Pinea Resort & Spa",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("bc56e33a-90e5-4dd6-8d6c-2d8d5b2842ec"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 34m,
                            Name = "Diamma Resort",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("ecccf797-9bd3-44de-b2fa-669d50f21add"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 31m,
                            Name = "Bonita Luxury Hotel",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("07d21c34-3815-45b6-b9d9-5f9d36390d19"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 90m,
                            Name = "Monte Carlo Vlora",
                            Street = "Rruga 28 Nentori"
                        },
                        new
                        {
                            Id = new Guid("acfec5b5-fc80-4b60-949f-9033878e2b8b"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 99m,
                            Name = "MonteCarlo Lungomare",
                            Street = "Rruga e Kavajes"
                        },
                        new
                        {
                            Id = new Guid("14400b6b-aede-49ee-b8d8-04fb4b3905a5"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 94m,
                            Name = "Mel Holidays",
                            Street = "Bulevardi Bajram Curri"
                        },
                        new
                        {
                            Id = new Guid("34616e7a-4e21-434d-926d-539d725eb506"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 74m,
                            Name = "Casa Durres",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("eb31ec37-64f2-4601-af16-78ebce930485"),
                            City = "Chania",
                            Country = "grecja",
                            FoodPricePerPerson = 91m,
                            Name = "Rethymno Mare Water Park",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("1ed9c18a-f0b1-4e6c-87dd-163b6a2889e5"),
                            City = "Peloponez",
                            Country = "grecja",
                            FoodPricePerPerson = 43m,
                            Name = "Aldemar Olympian Village",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("0e3d258a-4a1e-481d-84cd-4c6061d42f41"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 56m,
                            Name = "Studia Katerina",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("8355a31b-3d42-4ca9-8f1a-de89c2c6f7f7"),
                            City = "Heraklion",
                            Country = "grecja",
                            FoodPricePerPerson = 74m,
                            Name = "Irini Studios",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("7ac9b496-ed05-456e-90ac-57e0549cbe0a"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 110m,
                            Name = "Studia Maria",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("e33be7f5-1f5c-4d34-8f4e-011f52bd0ad6"),
                            City = "Olimpijska",
                            Country = "grecja",
                            FoodPricePerPerson = 31m,
                            Name = "Dias Apartments",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("71094e66-c0e9-4b25-a5e9-91fb652d9a20"),
                            City = "Marmaris",
                            Country = "turcja",
                            FoodPricePerPerson = 109m,
                            Name = "Turunc Resort",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("4e1bb7e6-e167-4c40-87d9-f26af0f8257a"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 111m,
                            Name = "Andriake Beach Club Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("19b1b5ec-e3a5-4a2d-a906-2d1ad4543586"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 114m,
                            Name = "Kimeros Park Holiday Village",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("d73ec87d-e9b9-455d-b1ec-3923fc73f903"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 35m,
                            Name = "Kleopatra Micador",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("8bb7a710-b8a8-4465-aab6-98daa7aa33ec"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 50m,
                            Name = "Melissa",
                            Street = "Halaskargazi Caddesi"
                        },
                        new
                        {
                            Id = new Guid("5e772585-4fd6-440f-b08d-a08f738ad291"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 107m,
                            Name = "Kolibri Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("2c782900-b4d8-47d5-a8cc-2043e2d73a1a"),
                            City = "Almeria",
                            Country = "hiszpania",
                            FoodPricePerPerson = 38m,
                            Name = "Evenia Zoraida Beach Resort",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("2dce53f9-d97e-44c9-aa2c-02c5c35771d6"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 96m,
                            Name = "Evenia Olympic Park",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("32eea1d8-1bd6-46df-972a-618b2c5528ed"),
                            City = "Luz",
                            Country = "hiszpania",
                            FoodPricePerPerson = 94m,
                            Name = "Estival Islantilla",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("67fb8245-df03-4171-9e44-d8e555887434"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 37m,
                            Name = "Cartago Nova by Alegria",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("e77797bf-2a87-4fbf-8dd4-a5aea3286c57"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 67m,
                            Name = "Catalonia",
                            Street = "Calle de Alcalá"
                        },
                        new
                        {
                            Id = new Guid("29c9409f-33fc-4a7f-9cca-5bf036c07399"),
                            City = "Maresme",
                            Country = "hiszpania",
                            FoodPricePerPerson = 106m,
                            Name = "Reymar Playa",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("6fbeefff-2a08-47aa-b7fa-1655ff65535d"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 77m,
                            Name = "GHT Oasis Park & Spa",
                            Street = "Gran Vía"
                        },
                        new
                        {
                            Id = new Guid("7e942bcf-3b00-439a-b14b-f994ad3d415a"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 79m,
                            Name = "San Domenico",
                            Street = "Via del Corso"
                        },
                        new
                        {
                            Id = new Guid("14e0707c-0301-47a7-a76b-152d758206bb"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 47m,
                            Name = "Baia di Zambrone",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("9731368d-d55f-44d6-aac5-e15eff3244c6"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 93m,
                            Name = "Rada Siri",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("e65198b8-d5e5-4e3a-89a2-cf04095ebd95"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 81m,
                            Name = "Hotel Orizzonte Blu",
                            Street = "Via Nazionale"
                        },
                        new
                        {
                            Id = new Guid("9a11a14d-596c-4cea-9025-a3ef6bc6db28"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 116m,
                            Name = "Gradac",
                            Street = "Kapucinska ulica"
                        },
                        new
                        {
                            Id = new Guid("8a243c8c-1266-494a-99f4-9d39649eee48"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 31m,
                            Name = "Villa Penava",
                            Street = "Trg bana Josipa Jelačića"
                        },
                        new
                        {
                            Id = new Guid("bb9d9253-ff63-4094-94a4-fd975be24636"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 42m,
                            Name = "Apartamenty Omiś",
                            Street = "Vukovarska ulica"
                        },
                        new
                        {
                            Id = new Guid("343af0b3-e699-4c8e-bb3b-7201beb68146"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 88m,
                            Name = "Nano",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("630f7b95-dc9c-4104-b4d4-d0789be5795a"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 83m,
                            Name = "Apartamenty Makarska",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("5e9c6d44-c0ca-482e-b08a-f7dbc3d927ad"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 97m,
                            Name = "Marina Resort Port Ghalib",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("0e08fd42-22d8-4515-91c4-8e2c50cfe813"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 76m,
                            Name = "Barcelo Tiran Sharm Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("58612880-0a43-466f-8bf1-c54cd7e6ee69"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 74m,
                            Name = "Old Vic Resort Sharm",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("740a04e9-bd95-4fa5-a82e-e29ff323d60b"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 33m,
                            Name = "Marina Lodge Port Ghalib",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("32c81ca3-eb02-4693-b77f-aa772c381317"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 116m,
                            Name = "Falcon Naama Star",
                            Street = "Sharia Salah Salem"
                        },
                        new
                        {
                            Id = new Guid("a1ac6ac7-2e97-4d5e-80af-2421b54fbc82"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 80m,
                            Name = "Protels Crystal Beach Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("cd4a7f10-06c9-4bc0-9708-55c1b80c4ab1"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 89m,
                            Name = "MG Alexander The Great",
                            Street = "Sharia Gamal Abdel Nasser"
                        },
                        new
                        {
                            Id = new Guid("d4d3cb37-9cde-4302-9036-753cae27f44a"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 83m,
                            Name = "Bliss Nada Beach Resort",
                            Street = "Sharia Tahrir"
                        });
                });

            modelBuilder.Entity("hotelservice.Models.PopularHotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PopularHotels");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87303120-804e-45b4-8faa-0d29b633c96c"),
                            Count = 3,
                            HotelId = new Guid("ccfd895c-3aea-4394-a6eb-a4527b204cec"),
                            Price = 119m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("5b223ec6-71c2-474d-95b8-3a0e5e5dfc39"),
                            Count = 2,
                            HotelId = new Guid("ccfd895c-3aea-4394-a6eb-a4527b204cec"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("dadd1092-96c0-4ad1-85b0-89427c865c7d"),
                            Count = 2,
                            HotelId = new Guid("ccfd895c-3aea-4394-a6eb-a4527b204cec"),
                            Price = 123m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("8de42fce-9e5e-47ef-a97e-2d1904bd4dbf"),
                            Count = 2,
                            HotelId = new Guid("ccfd895c-3aea-4394-a6eb-a4527b204cec"),
                            Price = 215m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("89e81191-b3fb-4b84-84f7-786a8ee7148b"),
                            Count = 2,
                            HotelId = new Guid("bc56e33a-90e5-4dd6-8d6c-2d8d5b2842ec"),
                            Price = 145m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e0f3d63f-cef7-4dbf-ac54-5e2de0f76ed3"),
                            Count = 2,
                            HotelId = new Guid("bc56e33a-90e5-4dd6-8d6c-2d8d5b2842ec"),
                            Price = 138m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3b453a94-7289-4c4c-9657-79c09b95b1e5"),
                            Count = 3,
                            HotelId = new Guid("bc56e33a-90e5-4dd6-8d6c-2d8d5b2842ec"),
                            Price = 74m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6b04696c-9508-4d33-b783-07e464701887"),
                            Count = 1,
                            HotelId = new Guid("bc56e33a-90e5-4dd6-8d6c-2d8d5b2842ec"),
                            Price = 205m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("57a783dc-41aa-4501-9895-d7a5731499c3"),
                            Count = 2,
                            HotelId = new Guid("ecccf797-9bd3-44de-b2fa-669d50f21add"),
                            Price = 186m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("bd307f61-46f9-42a2-b724-ad18b1b9734e"),
                            Count = 3,
                            HotelId = new Guid("ecccf797-9bd3-44de-b2fa-669d50f21add"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("845f1f13-8477-40c6-8be7-ea018cf6f9ac"),
                            Count = 1,
                            HotelId = new Guid("ecccf797-9bd3-44de-b2fa-669d50f21add"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1d809369-de6f-4efc-bc8f-5601c72a13ca"),
                            Count = 1,
                            HotelId = new Guid("ecccf797-9bd3-44de-b2fa-669d50f21add"),
                            Price = 69m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5c934c9f-eb67-4877-9be9-86aeec76cd99"),
                            Count = 1,
                            HotelId = new Guid("07d21c34-3815-45b6-b9d9-5f9d36390d19"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("7be8894f-de18-4a7c-8fbc-eb64cb9c96cf"),
                            Count = 3,
                            HotelId = new Guid("07d21c34-3815-45b6-b9d9-5f9d36390d19"),
                            Price = 147m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("776e23b2-bdb9-4f14-a811-f21be2c2656a"),
                            Count = 2,
                            HotelId = new Guid("07d21c34-3815-45b6-b9d9-5f9d36390d19"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d90a37a6-2e43-4c5b-a8cb-aaeadf93e8fa"),
                            Count = 3,
                            HotelId = new Guid("07d21c34-3815-45b6-b9d9-5f9d36390d19"),
                            Price = 110m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("28c04a84-4058-46cf-9c78-6676ec562a00"),
                            Count = 3,
                            HotelId = new Guid("acfec5b5-fc80-4b60-949f-9033878e2b8b"),
                            Price = 193m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("02fd38dc-beb4-4db4-a198-d3929bbbae6b"),
                            Count = 1,
                            HotelId = new Guid("acfec5b5-fc80-4b60-949f-9033878e2b8b"),
                            Price = 182m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b1698865-2290-463c-b63c-cf7ab2a64b7a"),
                            Count = 1,
                            HotelId = new Guid("acfec5b5-fc80-4b60-949f-9033878e2b8b"),
                            Price = 238m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ed1755b0-86c8-4a27-b7d7-2ee2e83632cc"),
                            Count = 3,
                            HotelId = new Guid("acfec5b5-fc80-4b60-949f-9033878e2b8b"),
                            Price = 70m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("cccdf7aa-621b-48d3-b821-5bb718227f09"),
                            Count = 3,
                            HotelId = new Guid("14400b6b-aede-49ee-b8d8-04fb4b3905a5"),
                            Price = 219m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4721c536-b128-4b3a-b637-54cc4402be15"),
                            Count = 3,
                            HotelId = new Guid("14400b6b-aede-49ee-b8d8-04fb4b3905a5"),
                            Price = 109m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c2c876bc-6342-4eb7-9ae4-cce1b0f1eecc"),
                            Count = 3,
                            HotelId = new Guid("14400b6b-aede-49ee-b8d8-04fb4b3905a5"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1087213d-b56d-47a8-b91e-0dc1721ca2b5"),
                            Count = 2,
                            HotelId = new Guid("14400b6b-aede-49ee-b8d8-04fb4b3905a5"),
                            Price = 143m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("be6f3dac-e254-42af-aec1-cbc711fd8ef4"),
                            Count = 3,
                            HotelId = new Guid("34616e7a-4e21-434d-926d-539d725eb506"),
                            Price = 104m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("14a8b9cc-e9b0-4c6e-a1d9-2c44d69783a7"),
                            Count = 1,
                            HotelId = new Guid("34616e7a-4e21-434d-926d-539d725eb506"),
                            Price = 136m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("5acb4e95-e52f-439d-ad6e-0dcb434dab2e"),
                            Count = 3,
                            HotelId = new Guid("34616e7a-4e21-434d-926d-539d725eb506"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ab09847f-c8d8-4bdb-92bd-6279ea422d4a"),
                            Count = 2,
                            HotelId = new Guid("34616e7a-4e21-434d-926d-539d725eb506"),
                            Price = 105m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ff488db8-2d27-461c-92da-4fa3bc223641"),
                            Count = 2,
                            HotelId = new Guid("eb31ec37-64f2-4601-af16-78ebce930485"),
                            Price = 211m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2be417c0-28b4-4900-84e0-3a9cb516e54a"),
                            Count = 1,
                            HotelId = new Guid("eb31ec37-64f2-4601-af16-78ebce930485"),
                            Price = 77m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3aee5d0b-5e34-48b6-b8ad-2696591f3794"),
                            Count = 2,
                            HotelId = new Guid("eb31ec37-64f2-4601-af16-78ebce930485"),
                            Price = 169m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("86804678-a5c0-4d90-b40d-7260c71159ce"),
                            Count = 1,
                            HotelId = new Guid("eb31ec37-64f2-4601-af16-78ebce930485"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("43557b33-ae80-4a12-a18f-df51d8c90112"),
                            Count = 2,
                            HotelId = new Guid("1ed9c18a-f0b1-4e6c-87dd-163b6a2889e5"),
                            Price = 239m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("59ae8e0e-e7cc-4c32-a399-9eb211a3437d"),
                            Count = 3,
                            HotelId = new Guid("1ed9c18a-f0b1-4e6c-87dd-163b6a2889e5"),
                            Price = 208m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3b223e26-ce4d-4c9f-bf74-25b5e26141e3"),
                            Count = 3,
                            HotelId = new Guid("1ed9c18a-f0b1-4e6c-87dd-163b6a2889e5"),
                            Price = 161m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("cb24b2d7-5c80-41b6-95ad-aac38bc73289"),
                            Count = 1,
                            HotelId = new Guid("1ed9c18a-f0b1-4e6c-87dd-163b6a2889e5"),
                            Price = 64m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("fbaf0602-3282-4d6a-b3fe-daa88463f319"),
                            Count = 1,
                            HotelId = new Guid("0e3d258a-4a1e-481d-84cd-4c6061d42f41"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d04b8460-7395-4018-bf12-70e5d9ca72cc"),
                            Count = 2,
                            HotelId = new Guid("0e3d258a-4a1e-481d-84cd-4c6061d42f41"),
                            Price = 234m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("283ba3e1-1d4e-4768-86c9-4879a4d29a60"),
                            Count = 3,
                            HotelId = new Guid("0e3d258a-4a1e-481d-84cd-4c6061d42f41"),
                            Price = 84m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f3c9cfc8-b8a5-4059-9e33-ae14766f3571"),
                            Count = 3,
                            HotelId = new Guid("0e3d258a-4a1e-481d-84cd-4c6061d42f41"),
                            Price = 216m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ea1b3028-4c6e-4aeb-b4a7-dad703b21627"),
                            Count = 2,
                            HotelId = new Guid("8355a31b-3d42-4ca9-8f1a-de89c2c6f7f7"),
                            Price = 165m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("646c376c-0b43-48b7-b9ba-8a11db4c4242"),
                            Count = 2,
                            HotelId = new Guid("8355a31b-3d42-4ca9-8f1a-de89c2c6f7f7"),
                            Price = 88m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8610e7b7-0f3e-4b0c-aa0f-f4fc24ea322e"),
                            Count = 1,
                            HotelId = new Guid("8355a31b-3d42-4ca9-8f1a-de89c2c6f7f7"),
                            Price = 210m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("54166cb8-5a46-485f-9e77-fac6f77d908f"),
                            Count = 1,
                            HotelId = new Guid("8355a31b-3d42-4ca9-8f1a-de89c2c6f7f7"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("97db0b4b-042f-4684-82ca-d11bbe3e9921"),
                            Count = 1,
                            HotelId = new Guid("7ac9b496-ed05-456e-90ac-57e0549cbe0a"),
                            Price = 130m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("bd76cc01-fed1-4692-b955-009d110a125e"),
                            Count = 3,
                            HotelId = new Guid("7ac9b496-ed05-456e-90ac-57e0549cbe0a"),
                            Price = 97m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("25186175-b09b-4c72-ad29-cda5f6743c6e"),
                            Count = 3,
                            HotelId = new Guid("7ac9b496-ed05-456e-90ac-57e0549cbe0a"),
                            Price = 165m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ac2b7e74-009d-47a3-b8ee-d9ac7bebf25a"),
                            Count = 1,
                            HotelId = new Guid("7ac9b496-ed05-456e-90ac-57e0549cbe0a"),
                            Price = 72m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("08fc5f97-ac7b-4c3d-95d8-e8a3b0a4d7f7"),
                            Count = 1,
                            HotelId = new Guid("e33be7f5-1f5c-4d34-8f4e-011f52bd0ad6"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("be22caee-e610-49e9-be36-9dcd8c47c60c"),
                            Count = 2,
                            HotelId = new Guid("e33be7f5-1f5c-4d34-8f4e-011f52bd0ad6"),
                            Price = 125m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("71cf39a1-c5fd-44d6-8984-f10d3536a45a"),
                            Count = 1,
                            HotelId = new Guid("e33be7f5-1f5c-4d34-8f4e-011f52bd0ad6"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("abf36b7a-ec8f-47c4-b177-73caf14078fc"),
                            Count = 1,
                            HotelId = new Guid("e33be7f5-1f5c-4d34-8f4e-011f52bd0ad6"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("089802eb-7632-42df-898f-0d6e25ef41b3"),
                            Count = 2,
                            HotelId = new Guid("71094e66-c0e9-4b25-a5e9-91fb652d9a20"),
                            Price = 207m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("db7ce806-7f5e-49fb-a08f-4626cd4d89a9"),
                            Count = 3,
                            HotelId = new Guid("71094e66-c0e9-4b25-a5e9-91fb652d9a20"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a69d4f07-756b-4ce2-83b3-06f2c267ed79"),
                            Count = 3,
                            HotelId = new Guid("71094e66-c0e9-4b25-a5e9-91fb652d9a20"),
                            Price = 146m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("0e502551-9242-489e-94cc-7e8a8b4abd4f"),
                            Count = 1,
                            HotelId = new Guid("71094e66-c0e9-4b25-a5e9-91fb652d9a20"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6f6590dd-dcc3-4afc-b8b3-b4fa3fd4fb9e"),
                            Count = 3,
                            HotelId = new Guid("4e1bb7e6-e167-4c40-87d9-f26af0f8257a"),
                            Price = 132m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9fe9e7a6-d782-47c6-9d8a-7613d2b329b2"),
                            Count = 2,
                            HotelId = new Guid("4e1bb7e6-e167-4c40-87d9-f26af0f8257a"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("22aab998-5761-45d7-aabd-2bba7657da35"),
                            Count = 1,
                            HotelId = new Guid("4e1bb7e6-e167-4c40-87d9-f26af0f8257a"),
                            Price = 243m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("bfac6c16-9ed1-4084-8e44-2992bedfe778"),
                            Count = 2,
                            HotelId = new Guid("4e1bb7e6-e167-4c40-87d9-f26af0f8257a"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("447ee16c-5b97-4b9c-8e41-613a0f476ad5"),
                            Count = 3,
                            HotelId = new Guid("19b1b5ec-e3a5-4a2d-a906-2d1ad4543586"),
                            Price = 148m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("b434d134-4283-48c3-bed0-09520b300597"),
                            Count = 2,
                            HotelId = new Guid("19b1b5ec-e3a5-4a2d-a906-2d1ad4543586"),
                            Price = 168m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("311c86cc-7f5a-407e-94bf-a3b32173faa8"),
                            Count = 3,
                            HotelId = new Guid("19b1b5ec-e3a5-4a2d-a906-2d1ad4543586"),
                            Price = 230m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("16e055dc-014d-4ba7-bdb9-523ca39cbfde"),
                            Count = 3,
                            HotelId = new Guid("19b1b5ec-e3a5-4a2d-a906-2d1ad4543586"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c85a0a64-5cc9-4045-b21a-a334fe11939b"),
                            Count = 1,
                            HotelId = new Guid("d73ec87d-e9b9-455d-b1ec-3923fc73f903"),
                            Price = 201m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("b78d20ae-b3e8-42d3-85d9-1ea2fa76e87f"),
                            Count = 2,
                            HotelId = new Guid("d73ec87d-e9b9-455d-b1ec-3923fc73f903"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d96a26d6-8463-4584-b949-574e881ac469"),
                            Count = 2,
                            HotelId = new Guid("d73ec87d-e9b9-455d-b1ec-3923fc73f903"),
                            Price = 76m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("93de73c6-0ed4-4bcc-8e82-db120ebd958b"),
                            Count = 1,
                            HotelId = new Guid("d73ec87d-e9b9-455d-b1ec-3923fc73f903"),
                            Price = 63m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1b1aee06-9b03-4f22-8b76-3c4d861701e9"),
                            Count = 1,
                            HotelId = new Guid("8bb7a710-b8a8-4465-aab6-98daa7aa33ec"),
                            Price = 175m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f1f328b1-07a5-4a1d-82ea-c93f92476b6d"),
                            Count = 1,
                            HotelId = new Guid("8bb7a710-b8a8-4465-aab6-98daa7aa33ec"),
                            Price = 245m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("46c301b5-6c24-41c3-a33b-d83d462bee8c"),
                            Count = 1,
                            HotelId = new Guid("8bb7a710-b8a8-4465-aab6-98daa7aa33ec"),
                            Price = 50m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("38fd1410-d3a8-4022-bfce-9906199dde24"),
                            Count = 1,
                            HotelId = new Guid("8bb7a710-b8a8-4465-aab6-98daa7aa33ec"),
                            Price = 219m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c7300df1-fc6f-4181-a15a-e9da23fd87b3"),
                            Count = 3,
                            HotelId = new Guid("5e772585-4fd6-440f-b08d-a08f738ad291"),
                            Price = 215m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e2186228-270e-4c0f-869d-8c315c2f3472"),
                            Count = 1,
                            HotelId = new Guid("5e772585-4fd6-440f-b08d-a08f738ad291"),
                            Price = 164m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("df133101-d490-42f5-9ddf-bab5c9a7bf15"),
                            Count = 3,
                            HotelId = new Guid("5e772585-4fd6-440f-b08d-a08f738ad291"),
                            Price = 163m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e7944ff9-e8f4-489c-8033-5224c0f6989e"),
                            Count = 2,
                            HotelId = new Guid("5e772585-4fd6-440f-b08d-a08f738ad291"),
                            Price = 247m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("29f8ecf6-cd11-4511-8b6d-43aa9e47d1ff"),
                            Count = 1,
                            HotelId = new Guid("2c782900-b4d8-47d5-a8cc-2043e2d73a1a"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0c4b3401-abc7-437a-86e5-a730ee8bfcd1"),
                            Count = 3,
                            HotelId = new Guid("2c782900-b4d8-47d5-a8cc-2043e2d73a1a"),
                            Price = 149m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("98c36d86-de06-4cdc-955e-61f568b324bb"),
                            Count = 3,
                            HotelId = new Guid("2c782900-b4d8-47d5-a8cc-2043e2d73a1a"),
                            Price = 197m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("66ad0888-0343-44bd-aef6-e39077dd19bf"),
                            Count = 2,
                            HotelId = new Guid("2c782900-b4d8-47d5-a8cc-2043e2d73a1a"),
                            Price = 237m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f1bf1b0c-e3da-480f-a1f2-1d865af617f3"),
                            Count = 2,
                            HotelId = new Guid("2dce53f9-d97e-44c9-aa2c-02c5c35771d6"),
                            Price = 87m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("525c8c79-20c4-4aa0-a46f-9b8ac705eafd"),
                            Count = 1,
                            HotelId = new Guid("2dce53f9-d97e-44c9-aa2c-02c5c35771d6"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4d5fb5e5-0728-4415-a6a2-e10ef13da792"),
                            Count = 3,
                            HotelId = new Guid("2dce53f9-d97e-44c9-aa2c-02c5c35771d6"),
                            Price = 70m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("97302417-58ff-445f-a4df-180041294218"),
                            Count = 3,
                            HotelId = new Guid("2dce53f9-d97e-44c9-aa2c-02c5c35771d6"),
                            Price = 184m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9ba3a219-eed2-4ad6-a212-617383cac61f"),
                            Count = 3,
                            HotelId = new Guid("32eea1d8-1bd6-46df-972a-618b2c5528ed"),
                            Price = 242m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e5e9ff1c-13ac-4e44-93e6-92922567dd9a"),
                            Count = 1,
                            HotelId = new Guid("32eea1d8-1bd6-46df-972a-618b2c5528ed"),
                            Price = 132m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1d316936-c10c-47b5-b2c7-bf107ca0edb8"),
                            Count = 3,
                            HotelId = new Guid("32eea1d8-1bd6-46df-972a-618b2c5528ed"),
                            Price = 142m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b52e42de-a836-4a01-b746-42e2c019b3d8"),
                            Count = 2,
                            HotelId = new Guid("32eea1d8-1bd6-46df-972a-618b2c5528ed"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7675a0e7-dec7-4999-9cb0-5cded9603b57"),
                            Count = 3,
                            HotelId = new Guid("67fb8245-df03-4171-9e44-d8e555887434"),
                            Price = 233m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3074aab3-40f1-48f6-a3e3-eb4ef44b9e34"),
                            Count = 3,
                            HotelId = new Guid("67fb8245-df03-4171-9e44-d8e555887434"),
                            Price = 204m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("0f096c12-71ab-45a7-958e-14e63cc2ee41"),
                            Count = 1,
                            HotelId = new Guid("67fb8245-df03-4171-9e44-d8e555887434"),
                            Price = 171m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1b0cfcbd-74db-492b-b15b-9efacf10ca5a"),
                            Count = 1,
                            HotelId = new Guid("67fb8245-df03-4171-9e44-d8e555887434"),
                            Price = 94m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7a773837-b454-4e40-a27c-992d14be45c6"),
                            Count = 1,
                            HotelId = new Guid("e77797bf-2a87-4fbf-8dd4-a5aea3286c57"),
                            Price = 53m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ca5aa750-fd7f-407d-b649-b09e7d1d0a9e"),
                            Count = 3,
                            HotelId = new Guid("e77797bf-2a87-4fbf-8dd4-a5aea3286c57"),
                            Price = 92m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bb56df56-d29d-4723-823a-fb80bfa450a5"),
                            Count = 3,
                            HotelId = new Guid("e77797bf-2a87-4fbf-8dd4-a5aea3286c57"),
                            Price = 250m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("47e8e728-489c-4375-9e22-654de74432ce"),
                            Count = 3,
                            HotelId = new Guid("e77797bf-2a87-4fbf-8dd4-a5aea3286c57"),
                            Price = 241m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7b31bf7f-19f4-4bb9-b260-b80e7e327160"),
                            Count = 3,
                            HotelId = new Guid("29c9409f-33fc-4a7f-9cca-5bf036c07399"),
                            Price = 190m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("60d3bd1b-9008-4921-8990-0e0a1a2fba63"),
                            Count = 1,
                            HotelId = new Guid("29c9409f-33fc-4a7f-9cca-5bf036c07399"),
                            Price = 112m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("9edac936-b610-4e78-8afc-f0602193461f"),
                            Count = 2,
                            HotelId = new Guid("29c9409f-33fc-4a7f-9cca-5bf036c07399"),
                            Price = 152m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("5e89364f-edc1-4849-ae7d-2646400f9397"),
                            Count = 1,
                            HotelId = new Guid("29c9409f-33fc-4a7f-9cca-5bf036c07399"),
                            Price = 177m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("83d2f531-b5e3-4313-8a5a-6ab2b1064561"),
                            Count = 2,
                            HotelId = new Guid("6fbeefff-2a08-47aa-b7fa-1655ff65535d"),
                            Price = 60m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("652f4710-8310-4c15-bc94-76f01077585c"),
                            Count = 3,
                            HotelId = new Guid("6fbeefff-2a08-47aa-b7fa-1655ff65535d"),
                            Price = 190m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ed615cb2-f110-4190-aad5-6e06eb1603b6"),
                            Count = 3,
                            HotelId = new Guid("6fbeefff-2a08-47aa-b7fa-1655ff65535d"),
                            Price = 77m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("500301a1-cb34-4c5e-bedc-7980ec05cc65"),
                            Count = 3,
                            HotelId = new Guid("6fbeefff-2a08-47aa-b7fa-1655ff65535d"),
                            Price = 217m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7e20f897-6b0f-4fd7-893b-dffa3323ad73"),
                            Count = 1,
                            HotelId = new Guid("7e942bcf-3b00-439a-b14b-f994ad3d415a"),
                            Price = 146m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("27f2431c-1fa2-4d18-bd7b-d796d6212589"),
                            Count = 3,
                            HotelId = new Guid("7e942bcf-3b00-439a-b14b-f994ad3d415a"),
                            Price = 107m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1530baed-527f-4fb9-9f8a-8ca45dbd518b"),
                            Count = 1,
                            HotelId = new Guid("7e942bcf-3b00-439a-b14b-f994ad3d415a"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("0eee5a3d-dd3d-4ece-9da0-9da15a7af20b"),
                            Count = 3,
                            HotelId = new Guid("7e942bcf-3b00-439a-b14b-f994ad3d415a"),
                            Price = 162m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2648a400-3ee7-4c01-b76a-73389abeaf3f"),
                            Count = 2,
                            HotelId = new Guid("14e0707c-0301-47a7-a76b-152d758206bb"),
                            Price = 213m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f23fc848-c88c-42b2-b6a5-eebbb2385ad8"),
                            Count = 2,
                            HotelId = new Guid("14e0707c-0301-47a7-a76b-152d758206bb"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1d67742a-e447-43cc-ae27-7cb577e66d6f"),
                            Count = 2,
                            HotelId = new Guid("14e0707c-0301-47a7-a76b-152d758206bb"),
                            Price = 140m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("54293a1c-ee8d-4336-a946-da649dd8d4d0"),
                            Count = 2,
                            HotelId = new Guid("14e0707c-0301-47a7-a76b-152d758206bb"),
                            Price = 250m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("be132ee4-46cd-4395-809c-6e73846c9f05"),
                            Count = 3,
                            HotelId = new Guid("9731368d-d55f-44d6-aac5-e15eff3244c6"),
                            Price = 178m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c9880fda-6eeb-467b-a08f-4fc527aad604"),
                            Count = 3,
                            HotelId = new Guid("9731368d-d55f-44d6-aac5-e15eff3244c6"),
                            Price = 216m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("653904a3-f1a4-46c5-a234-ffc5535acb3b"),
                            Count = 1,
                            HotelId = new Guid("9731368d-d55f-44d6-aac5-e15eff3244c6"),
                            Price = 98m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("a0884426-4c0b-4b8e-913e-e2808165b95f"),
                            Count = 3,
                            HotelId = new Guid("9731368d-d55f-44d6-aac5-e15eff3244c6"),
                            Price = 165m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("64a90dff-1166-45e7-9a2c-09cc78b7b40e"),
                            Count = 3,
                            HotelId = new Guid("e65198b8-d5e5-4e3a-89a2-cf04095ebd95"),
                            Price = 118m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3130feaa-a6b7-4082-9096-c5fe4e0a4597"),
                            Count = 2,
                            HotelId = new Guid("e65198b8-d5e5-4e3a-89a2-cf04095ebd95"),
                            Price = 73m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("426b4a5b-2b9e-4da9-b290-990a7cb7016f"),
                            Count = 1,
                            HotelId = new Guid("e65198b8-d5e5-4e3a-89a2-cf04095ebd95"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("fb8aa155-8543-4459-9c69-ee32a8272e21"),
                            Count = 2,
                            HotelId = new Guid("e65198b8-d5e5-4e3a-89a2-cf04095ebd95"),
                            Price = 81m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2dfd89d5-3363-403e-8b96-e8d8b3f061c5"),
                            Count = 2,
                            HotelId = new Guid("9a11a14d-596c-4cea-9025-a3ef6bc6db28"),
                            Price = 111m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ac5720e3-ca6e-44ae-abbe-04ae2d4b7f96"),
                            Count = 1,
                            HotelId = new Guid("9a11a14d-596c-4cea-9025-a3ef6bc6db28"),
                            Price = 110m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e28dfb22-b171-4f28-99fa-8e3e2876fcb0"),
                            Count = 1,
                            HotelId = new Guid("9a11a14d-596c-4cea-9025-a3ef6bc6db28"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7a2cef6c-5c47-4800-9c2f-057bf4c5e25a"),
                            Count = 3,
                            HotelId = new Guid("9a11a14d-596c-4cea-9025-a3ef6bc6db28"),
                            Price = 239m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2a40886f-15d9-4dfc-857d-b783cd29242a"),
                            Count = 1,
                            HotelId = new Guid("8a243c8c-1266-494a-99f4-9d39649eee48"),
                            Price = 121m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2bb64ab0-5e8f-4879-a1ca-52193a5f16bd"),
                            Count = 1,
                            HotelId = new Guid("8a243c8c-1266-494a-99f4-9d39649eee48"),
                            Price = 187m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("12bd0ce3-14b6-459c-8fda-6209c7dcb446"),
                            Count = 2,
                            HotelId = new Guid("8a243c8c-1266-494a-99f4-9d39649eee48"),
                            Price = 201m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d8c1beb7-1554-4e1b-b4cb-887bfc513f00"),
                            Count = 1,
                            HotelId = new Guid("8a243c8c-1266-494a-99f4-9d39649eee48"),
                            Price = 73m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2969a7c7-2a4c-42ea-b4a9-36bf959899e1"),
                            Count = 3,
                            HotelId = new Guid("bb9d9253-ff63-4094-94a4-fd975be24636"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1e3d6c02-b4a4-4551-bf8a-6773fc877b0c"),
                            Count = 1,
                            HotelId = new Guid("bb9d9253-ff63-4094-94a4-fd975be24636"),
                            Price = 145m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("13659563-2741-4aa7-819f-7a55beb14abe"),
                            Count = 2,
                            HotelId = new Guid("bb9d9253-ff63-4094-94a4-fd975be24636"),
                            Price = 221m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("3dbd4394-8dd9-4a9f-b01d-28380128d0cf"),
                            Count = 2,
                            HotelId = new Guid("bb9d9253-ff63-4094-94a4-fd975be24636"),
                            Price = 108m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("99b7216d-68a8-4117-807c-33ba673e7aca"),
                            Count = 2,
                            HotelId = new Guid("343af0b3-e699-4c8e-bb3b-7201beb68146"),
                            Price = 220m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("860a515f-eb41-4dfb-891d-0294527a896a"),
                            Count = 2,
                            HotelId = new Guid("343af0b3-e699-4c8e-bb3b-7201beb68146"),
                            Price = 96m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2dd0e472-2bd7-4b20-8155-023a9192c6d6"),
                            Count = 1,
                            HotelId = new Guid("343af0b3-e699-4c8e-bb3b-7201beb68146"),
                            Price = 143m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7aa54a47-33b1-48ed-adf5-748a95188b38"),
                            Count = 3,
                            HotelId = new Guid("343af0b3-e699-4c8e-bb3b-7201beb68146"),
                            Price = 71m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1d3ea281-5a86-459a-93b0-bf82a241ce87"),
                            Count = 2,
                            HotelId = new Guid("630f7b95-dc9c-4104-b4d4-d0789be5795a"),
                            Price = 179m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4b260e8b-3b75-4b12-a29f-c5fef9c35fb8"),
                            Count = 3,
                            HotelId = new Guid("630f7b95-dc9c-4104-b4d4-d0789be5795a"),
                            Price = 155m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bed5dd62-3b6a-4c53-bf69-24b5432fa4ea"),
                            Count = 1,
                            HotelId = new Guid("630f7b95-dc9c-4104-b4d4-d0789be5795a"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9c14b67e-1bd4-4189-bd3d-8ae3401fc631"),
                            Count = 1,
                            HotelId = new Guid("630f7b95-dc9c-4104-b4d4-d0789be5795a"),
                            Price = 195m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("da006c59-7c80-4703-8853-3622561a29d4"),
                            Count = 2,
                            HotelId = new Guid("5e9c6d44-c0ca-482e-b08a-f7dbc3d927ad"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("95c8fd90-a90f-4946-832f-79d50071c41c"),
                            Count = 3,
                            HotelId = new Guid("5e9c6d44-c0ca-482e-b08a-f7dbc3d927ad"),
                            Price = 195m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("08e2e893-9869-48a3-82d7-a35a5f94a9c8"),
                            Count = 3,
                            HotelId = new Guid("5e9c6d44-c0ca-482e-b08a-f7dbc3d927ad"),
                            Price = 180m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4a7196da-7e94-40ba-af25-2f0957a2035a"),
                            Count = 3,
                            HotelId = new Guid("5e9c6d44-c0ca-482e-b08a-f7dbc3d927ad"),
                            Price = 210m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("fe6030b1-f5b6-4e22-9cd7-4ea9a2edadbb"),
                            Count = 2,
                            HotelId = new Guid("0e08fd42-22d8-4515-91c4-8e2c50cfe813"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dd25a843-980c-4321-82a6-e19d92b4bdee"),
                            Count = 2,
                            HotelId = new Guid("0e08fd42-22d8-4515-91c4-8e2c50cfe813"),
                            Price = 221m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ca8e9442-e180-4786-9d98-b7bf53c0f12c"),
                            Count = 3,
                            HotelId = new Guid("0e08fd42-22d8-4515-91c4-8e2c50cfe813"),
                            Price = 223m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("91b91bb6-649a-4454-892a-077f2f989108"),
                            Count = 3,
                            HotelId = new Guid("0e08fd42-22d8-4515-91c4-8e2c50cfe813"),
                            Price = 135m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3c2c28d4-ac7e-4d50-ae79-4d3e042c8964"),
                            Count = 2,
                            HotelId = new Guid("58612880-0a43-466f-8bf1-c54cd7e6ee69"),
                            Price = 66m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d834ba45-caef-4c8d-a2ff-8b7f268c309a"),
                            Count = 2,
                            HotelId = new Guid("58612880-0a43-466f-8bf1-c54cd7e6ee69"),
                            Price = 179m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6d444c35-0c77-40ae-abf0-36fa13a07bab"),
                            Count = 2,
                            HotelId = new Guid("58612880-0a43-466f-8bf1-c54cd7e6ee69"),
                            Price = 125m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("fa4b998c-80ec-467e-a9cc-728ae977cef1"),
                            Count = 2,
                            HotelId = new Guid("58612880-0a43-466f-8bf1-c54cd7e6ee69"),
                            Price = 147m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6c5e3290-8890-4fde-bb55-843ede9cbdd1"),
                            Count = 2,
                            HotelId = new Guid("740a04e9-bd95-4fa5-a82e-e29ff323d60b"),
                            Price = 176m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("646809f1-1e5f-42c3-8fb5-e4b24a98ba5f"),
                            Count = 3,
                            HotelId = new Guid("740a04e9-bd95-4fa5-a82e-e29ff323d60b"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("36c7b9fb-0833-435d-ad27-f958fa92fb3b"),
                            Count = 3,
                            HotelId = new Guid("740a04e9-bd95-4fa5-a82e-e29ff323d60b"),
                            Price = 127m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("60f34ba4-21db-49bf-9f10-f53f190fd3f1"),
                            Count = 3,
                            HotelId = new Guid("740a04e9-bd95-4fa5-a82e-e29ff323d60b"),
                            Price = 88m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c9566d1f-7bfd-441d-8827-bcb4da2f58c9"),
                            Count = 1,
                            HotelId = new Guid("32c81ca3-eb02-4693-b77f-aa772c381317"),
                            Price = 158m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("968cd4e3-15ea-4c8c-b99a-cc4751a17423"),
                            Count = 2,
                            HotelId = new Guid("32c81ca3-eb02-4693-b77f-aa772c381317"),
                            Price = 133m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("35d40519-316a-4baa-ac26-a61551c23ead"),
                            Count = 3,
                            HotelId = new Guid("32c81ca3-eb02-4693-b77f-aa772c381317"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("475a9e44-576c-4663-94c3-0348a14de592"),
                            Count = 3,
                            HotelId = new Guid("32c81ca3-eb02-4693-b77f-aa772c381317"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1879405c-b19f-4fd1-a657-cdda9f43b161"),
                            Count = 3,
                            HotelId = new Guid("a1ac6ac7-2e97-4d5e-80af-2421b54fbc82"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("a5f0a7e7-f489-4a49-96a0-79b8920f8961"),
                            Count = 2,
                            HotelId = new Guid("a1ac6ac7-2e97-4d5e-80af-2421b54fbc82"),
                            Price = 62m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1ae5dc58-dc98-47ef-ba93-b7da8a1b7dab"),
                            Count = 2,
                            HotelId = new Guid("a1ac6ac7-2e97-4d5e-80af-2421b54fbc82"),
                            Price = 162m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f965bc4a-a531-4450-9be8-8e5e0a2bbace"),
                            Count = 3,
                            HotelId = new Guid("a1ac6ac7-2e97-4d5e-80af-2421b54fbc82"),
                            Price = 191m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3524717c-338e-4156-96ff-ee5d1b23d01e"),
                            Count = 2,
                            HotelId = new Guid("cd4a7f10-06c9-4bc0-9708-55c1b80c4ab1"),
                            Price = 188m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("a013b730-eb2e-4eb1-a352-aa9216cf7fe5"),
                            Count = 2,
                            HotelId = new Guid("cd4a7f10-06c9-4bc0-9708-55c1b80c4ab1"),
                            Price = 90m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bec352ef-ab2d-46a0-9348-59fd5d61dc0c"),
                            Count = 2,
                            HotelId = new Guid("cd4a7f10-06c9-4bc0-9708-55c1b80c4ab1"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("60b0e204-816f-4001-a8df-a29d232332a4"),
                            Count = 2,
                            HotelId = new Guid("cd4a7f10-06c9-4bc0-9708-55c1b80c4ab1"),
                            Price = 209m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2d61cc56-6e28-4a75-a89e-17bfe35d2983"),
                            Count = 1,
                            HotelId = new Guid("d4d3cb37-9cde-4302-9036-753cae27f44a"),
                            Price = 123m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("293dfebd-1ab1-4c7c-9871-8cb5d8e09429"),
                            Count = 1,
                            HotelId = new Guid("d4d3cb37-9cde-4302-9036-753cae27f44a"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c1f5fe50-99e8-469f-9218-bf0d705ac70f"),
                            Count = 1,
                            HotelId = new Guid("d4d3cb37-9cde-4302-9036-753cae27f44a"),
                            Price = 218m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("da35772d-8383-4c37-88c3-812c0a885a95"),
                            Count = 1,
                            HotelId = new Guid("d4d3cb37-9cde-4302-9036-753cae27f44a"),
                            Price = 235m,
                            Size = 5
                        });
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomsReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Discounts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.HasOne("hotelservice.Models.Room", null)
                        .WithMany("Bookings")
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
