// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hotelservice.Models;

#nullable disable

namespace hotelservice.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240527223935_ScrappedHotels")]
    partial class ScrappedHotels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodPricePerPerson")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d492ac49-473f-40af-a22e-8a09677a4f77"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 103m,
                            Name = "Pinea Resort & Spa",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("665e3853-5f15-41d7-b1b5-ca6dc35270d1"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 110m,
                            Name = "Diamma Resort",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("17c2a049-354a-4ee9-970b-bebafa860d0b"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 101m,
                            Name = "Bonita Luxury Hotel",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("b77dcf11-ac64-41c1-b658-fdfe1b722440"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 44m,
                            Name = "Monte Carlo Vlora",
                            Street = "Rruga 28 Nentori"
                        },
                        new
                        {
                            Id = new Guid("3254d8e1-ade4-4269-afbb-8700239b983e"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 119m,
                            Name = "MonteCarlo Lungomare",
                            Street = "Rruga e Kavajes"
                        },
                        new
                        {
                            Id = new Guid("fcf46a5d-0ca7-4f75-a75e-92d4e4fcfe64"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 102m,
                            Name = "Mel Holidays",
                            Street = "Bulevardi Bajram Curri"
                        },
                        new
                        {
                            Id = new Guid("8fb1730f-da85-49ae-910e-558ff4d2e364"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 40m,
                            Name = "Casa Durres",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("1074a13e-c554-433c-a3e4-50564106b112"),
                            City = "Chania",
                            Country = "grecja",
                            FoodPricePerPerson = 37m,
                            Name = "Rethymno Mare Water Park",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("90f8336e-35db-4c21-af68-411ee95df62c"),
                            City = "Peloponez",
                            Country = "grecja",
                            FoodPricePerPerson = 31m,
                            Name = "Aldemar Olympian Village",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("ee56336a-9aab-45e9-b0f1-383e9897baf9"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 80m,
                            Name = "Studia Katerina",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("5219e274-fc18-4abf-b431-a15d0c0980a7"),
                            City = "Heraklion",
                            Country = "grecja",
                            FoodPricePerPerson = 85m,
                            Name = "Irini Studios",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("390d22d9-89cb-4b5b-8ed2-db63c20c1fe0"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 90m,
                            Name = "Studia Maria",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("384e7d47-f9e4-432e-9036-34d6da8152eb"),
                            City = "Olimpijska",
                            Country = "grecja",
                            FoodPricePerPerson = 86m,
                            Name = "Dias Apartments",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("4d41a2f3-e79d-47f6-93e3-31990462b67c"),
                            City = "Marmaris",
                            Country = "turcja",
                            FoodPricePerPerson = 65m,
                            Name = "Turunc Resort",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("fb56e927-a622-46fd-82a7-32bb2c3e30b2"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 119m,
                            Name = "Andriake Beach Club Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("91492bb1-767f-4b58-829f-e4475a314d1a"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 90m,
                            Name = "Kimeros Park Holiday Village",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("832de1a7-b9d9-4bbc-8a4b-c9f68cb0e6fb"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 81m,
                            Name = "Kleopatra Micador",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("c0a97197-ac51-41ab-a63b-340a31f8d25a"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 82m,
                            Name = "Melissa",
                            Street = "Halaskargazi Caddesi"
                        },
                        new
                        {
                            Id = new Guid("392a2517-d760-4f0c-bf1b-3f76ed2a5b5d"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 45m,
                            Name = "Kolibri Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("33c07c58-128d-4230-b102-2d75ec3f5c6c"),
                            City = "Almeria",
                            Country = "hiszpania",
                            FoodPricePerPerson = 119m,
                            Name = "Evenia Zoraida Beach Resort",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("f869ad97-26c7-45e5-b83c-85723f9867bf"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 76m,
                            Name = "Evenia Olympic Park",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("9699fea0-c651-4a40-828c-1b3e304c3edc"),
                            City = "Luz",
                            Country = "hiszpania",
                            FoodPricePerPerson = 45m,
                            Name = "Estival Islantilla",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("b5dfb131-8042-4bec-ac0e-adc3a18d75d0"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 82m,
                            Name = "Cartago Nova by Alegria",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("fa68ad5b-ffbe-48ae-9f93-8fa94bf7226c"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 60m,
                            Name = "Catalonia",
                            Street = "Calle de Alcalá"
                        },
                        new
                        {
                            Id = new Guid("12b63b13-0780-4dd0-bf96-564594543b79"),
                            City = "Maresme",
                            Country = "hiszpania",
                            FoodPricePerPerson = 84m,
                            Name = "Reymar Playa",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("ca7c8aaf-de51-46e6-95f7-f7147440b528"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 66m,
                            Name = "GHT Oasis Park & Spa",
                            Street = "Gran Vía"
                        },
                        new
                        {
                            Id = new Guid("83ce943a-f3df-4fb5-9c37-a659b5afc2c8"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 73m,
                            Name = "San Domenico",
                            Street = "Via del Corso"
                        },
                        new
                        {
                            Id = new Guid("fd285982-c0cf-4a0c-b248-0b194c17210c"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 109m,
                            Name = "Baia di Zambrone",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("c94df083-fc2a-4695-8493-f02af5db384b"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 70m,
                            Name = "Rada Siri",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("76a510f4-a1ee-40e7-8236-7b58e0772d98"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 90m,
                            Name = "Hotel Orizzonte Blu",
                            Street = "Via Nazionale"
                        },
                        new
                        {
                            Id = new Guid("887a924c-5946-4819-b49c-70a717b9ff2f"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 92m,
                            Name = "Gradac",
                            Street = "Kapucinska ulica"
                        },
                        new
                        {
                            Id = new Guid("bbf5e021-266d-4020-8279-b6df7f250f53"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 100m,
                            Name = "Villa Penava",
                            Street = "Trg bana Josipa Jelačića"
                        },
                        new
                        {
                            Id = new Guid("984962a4-b362-4e3b-a8c3-5124c19ed106"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 84m,
                            Name = "Apartamenty Omiś",
                            Street = "Vukovarska ulica"
                        },
                        new
                        {
                            Id = new Guid("1eba02c2-00f8-4190-a118-d4970c7de667"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 30m,
                            Name = "Nano",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("57b599b2-ea69-400c-80b8-f2222e2cf10c"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 37m,
                            Name = "Apartamenty Makarska",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("c5fcc3f1-ae51-4f8d-93a3-3cbceadd8029"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 74m,
                            Name = "Marina Resort Port Ghalib",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("9e0b4c5e-37d8-45cd-a054-e0287686b5ed"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 87m,
                            Name = "Barcelo Tiran Sharm Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("593235a6-71b4-4f1b-814f-8338e22fe404"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 76m,
                            Name = "Old Vic Resort Sharm",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("6bc5772a-43c7-4d16-b56a-2fd0f5576681"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 118m,
                            Name = "Marina Lodge Port Ghalib",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("44933f93-2830-46bd-bb3f-90a47a8dd8d3"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 62m,
                            Name = "Falcon Naama Star",
                            Street = "Sharia Salah Salem"
                        },
                        new
                        {
                            Id = new Guid("61b21151-7cf1-4482-a3dc-37f169d554e1"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 86m,
                            Name = "Protels Crystal Beach Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("318a37a9-8132-4cb5-bab1-df114dafabf4"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 98m,
                            Name = "MG Alexander The Great",
                            Street = "Sharia Gamal Abdel Nasser"
                        },
                        new
                        {
                            Id = new Guid("b28d50e4-41b0-403b-af83-5a0c5f733173"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 75m,
                            Name = "Bliss Nada Beach Resort",
                            Street = "Sharia Tahrir"
                        });
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40c51aa1-1dcc-4404-bcab-a6db383313d6"),
                            Count = 1,
                            HotelId = new Guid("d492ac49-473f-40af-a22e-8a09677a4f77"),
                            Price = 118m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9db5fcdb-4dba-4105-9678-6ae3874745ff"),
                            Count = 3,
                            HotelId = new Guid("d492ac49-473f-40af-a22e-8a09677a4f77"),
                            Price = 201m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ea5c9dab-5f14-4b34-af64-3b3ae9a4c69b"),
                            Count = 1,
                            HotelId = new Guid("d492ac49-473f-40af-a22e-8a09677a4f77"),
                            Price = 76m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("a953dcf5-8355-4fab-be62-7df4bf005084"),
                            Count = 2,
                            HotelId = new Guid("d492ac49-473f-40af-a22e-8a09677a4f77"),
                            Price = 149m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4a0367a7-d5e8-4aa8-9df2-9980ec300952"),
                            Count = 2,
                            HotelId = new Guid("665e3853-5f15-41d7-b1b5-ca6dc35270d1"),
                            Price = 202m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c1dfdf73-4c9d-4615-8d43-dae9ce364982"),
                            Count = 1,
                            HotelId = new Guid("665e3853-5f15-41d7-b1b5-ca6dc35270d1"),
                            Price = 209m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("13e992a5-e98c-4adf-8f87-7353cf4223d2"),
                            Count = 3,
                            HotelId = new Guid("665e3853-5f15-41d7-b1b5-ca6dc35270d1"),
                            Price = 57m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("04c45f0f-31bb-450e-a0bd-5810b20f48a4"),
                            Count = 3,
                            HotelId = new Guid("665e3853-5f15-41d7-b1b5-ca6dc35270d1"),
                            Price = 151m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1418ece0-c1ed-4510-90f8-90a2e3550205"),
                            Count = 3,
                            HotelId = new Guid("17c2a049-354a-4ee9-970b-bebafa860d0b"),
                            Price = 50m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("45b6e24b-be1d-4043-bbb2-7cd307712ed6"),
                            Count = 2,
                            HotelId = new Guid("17c2a049-354a-4ee9-970b-bebafa860d0b"),
                            Price = 149m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("7278811a-2838-4d30-b246-01dbe87bb948"),
                            Count = 3,
                            HotelId = new Guid("17c2a049-354a-4ee9-970b-bebafa860d0b"),
                            Price = 118m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2c4a9505-3173-48de-9c5f-4f6322a78f45"),
                            Count = 2,
                            HotelId = new Guid("17c2a049-354a-4ee9-970b-bebafa860d0b"),
                            Price = 192m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("89bcb243-605e-4969-a9da-04bb1b6930a2"),
                            Count = 3,
                            HotelId = new Guid("b77dcf11-ac64-41c1-b658-fdfe1b722440"),
                            Price = 196m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d9cc568d-70b0-49ca-aae5-71c613129469"),
                            Count = 1,
                            HotelId = new Guid("b77dcf11-ac64-41c1-b658-fdfe1b722440"),
                            Price = 134m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c057e082-602f-4122-8e3c-2af7246567d8"),
                            Count = 2,
                            HotelId = new Guid("b77dcf11-ac64-41c1-b658-fdfe1b722440"),
                            Price = 87m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d0a3f9dd-4bc2-47ff-952a-46065f7236d7"),
                            Count = 1,
                            HotelId = new Guid("b77dcf11-ac64-41c1-b658-fdfe1b722440"),
                            Price = 192m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b0094f58-91d3-4cba-a057-0761c3398e4a"),
                            Count = 1,
                            HotelId = new Guid("3254d8e1-ade4-4269-afbb-8700239b983e"),
                            Price = 103m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("54263b90-b24d-4ed5-a5eb-a1f878c0c686"),
                            Count = 3,
                            HotelId = new Guid("3254d8e1-ade4-4269-afbb-8700239b983e"),
                            Price = 147m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e6a38b14-c923-43b0-a2b3-fab56f8b4477"),
                            Count = 1,
                            HotelId = new Guid("3254d8e1-ade4-4269-afbb-8700239b983e"),
                            Price = 87m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6687abb6-e85e-4816-9240-afa23c80a4f5"),
                            Count = 2,
                            HotelId = new Guid("3254d8e1-ade4-4269-afbb-8700239b983e"),
                            Price = 196m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9d6b3e15-5c44-41ae-8cb7-2d9c0bb5e03f"),
                            Count = 1,
                            HotelId = new Guid("fcf46a5d-0ca7-4f75-a75e-92d4e4fcfe64"),
                            Price = 163m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("849a08c6-5daa-4884-833d-4cbbc8a7740e"),
                            Count = 2,
                            HotelId = new Guid("fcf46a5d-0ca7-4f75-a75e-92d4e4fcfe64"),
                            Price = 165m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f3172922-148a-42b0-a71d-bc14cd3e1e73"),
                            Count = 2,
                            HotelId = new Guid("fcf46a5d-0ca7-4f75-a75e-92d4e4fcfe64"),
                            Price = 152m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7b7afac8-cbd5-4524-9389-b6086d26cda3"),
                            Count = 1,
                            HotelId = new Guid("fcf46a5d-0ca7-4f75-a75e-92d4e4fcfe64"),
                            Price = 165m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("694dd827-981e-4980-b736-9a27cd33e247"),
                            Count = 3,
                            HotelId = new Guid("8fb1730f-da85-49ae-910e-558ff4d2e364"),
                            Price = 197m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("60f3d306-da90-4524-a501-9aba826e39cd"),
                            Count = 3,
                            HotelId = new Guid("8fb1730f-da85-49ae-910e-558ff4d2e364"),
                            Price = 167m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f834404a-7693-464a-bb65-e8ad363414be"),
                            Count = 1,
                            HotelId = new Guid("8fb1730f-da85-49ae-910e-558ff4d2e364"),
                            Price = 91m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f13b3ac5-d662-455d-b136-f5094f1c0957"),
                            Count = 2,
                            HotelId = new Guid("8fb1730f-da85-49ae-910e-558ff4d2e364"),
                            Price = 190m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("5a2c6e11-c61d-4c56-93a5-1eb1d2efcdd2"),
                            Count = 2,
                            HotelId = new Guid("1074a13e-c554-433c-a3e4-50564106b112"),
                            Price = 176m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3f5c0faa-0372-4aaa-bd6c-011758facc2d"),
                            Count = 3,
                            HotelId = new Guid("1074a13e-c554-433c-a3e4-50564106b112"),
                            Price = 62m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("24004a7d-8948-4036-9c6e-44afe5f5a2db"),
                            Count = 1,
                            HotelId = new Guid("1074a13e-c554-433c-a3e4-50564106b112"),
                            Price = 205m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("70e4dd97-5e09-4fca-aadc-4b88a3883094"),
                            Count = 3,
                            HotelId = new Guid("1074a13e-c554-433c-a3e4-50564106b112"),
                            Price = 183m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("726e803d-bed0-48f0-b30f-bce375ef4cdc"),
                            Count = 3,
                            HotelId = new Guid("90f8336e-35db-4c21-af68-411ee95df62c"),
                            Price = 186m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("5c13a966-2cab-4b1f-b67a-4fba7687f54a"),
                            Count = 1,
                            HotelId = new Guid("90f8336e-35db-4c21-af68-411ee95df62c"),
                            Price = 113m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("949746a0-5da5-4b2d-9780-24b028531826"),
                            Count = 2,
                            HotelId = new Guid("90f8336e-35db-4c21-af68-411ee95df62c"),
                            Price = 161m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("57a98880-8f0c-4336-bbc8-005e44820d6e"),
                            Count = 1,
                            HotelId = new Guid("90f8336e-35db-4c21-af68-411ee95df62c"),
                            Price = 235m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9dc2fadd-db14-44ab-99be-c622d61708fd"),
                            Count = 1,
                            HotelId = new Guid("ee56336a-9aab-45e9-b0f1-383e9897baf9"),
                            Price = 92m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("54ad1dcb-4e4a-4f02-97e1-0b2b3dbe22c8"),
                            Count = 2,
                            HotelId = new Guid("ee56336a-9aab-45e9-b0f1-383e9897baf9"),
                            Price = 214m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("803fc3f1-e31b-43f1-b258-875c28bf4bf8"),
                            Count = 3,
                            HotelId = new Guid("ee56336a-9aab-45e9-b0f1-383e9897baf9"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("593a4bf8-18ce-433d-bb7a-c9f80747fa14"),
                            Count = 3,
                            HotelId = new Guid("ee56336a-9aab-45e9-b0f1-383e9897baf9"),
                            Price = 148m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("d411eef2-c4dc-45f7-bda9-2280254ffce0"),
                            Count = 3,
                            HotelId = new Guid("5219e274-fc18-4abf-b431-a15d0c0980a7"),
                            Price = 146m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4a6d17ae-1869-4f74-bb28-ed9748528a85"),
                            Count = 3,
                            HotelId = new Guid("5219e274-fc18-4abf-b431-a15d0c0980a7"),
                            Price = 133m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f0f05172-bcf3-4183-b6db-77a7e3146721"),
                            Count = 3,
                            HotelId = new Guid("5219e274-fc18-4abf-b431-a15d0c0980a7"),
                            Price = 186m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("86dbb60f-1d3f-45c9-8a04-4a2135c6c852"),
                            Count = 1,
                            HotelId = new Guid("5219e274-fc18-4abf-b431-a15d0c0980a7"),
                            Price = 146m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1b42c77c-949c-4be3-b950-c7ce324dbe54"),
                            Count = 3,
                            HotelId = new Guid("390d22d9-89cb-4b5b-8ed2-db63c20c1fe0"),
                            Price = 206m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("0430961d-58e0-47ba-aa32-9917a663afd6"),
                            Count = 1,
                            HotelId = new Guid("390d22d9-89cb-4b5b-8ed2-db63c20c1fe0"),
                            Price = 181m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ba987fb6-1afb-4e2f-bea0-875d4b082714"),
                            Count = 1,
                            HotelId = new Guid("390d22d9-89cb-4b5b-8ed2-db63c20c1fe0"),
                            Price = 185m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2fdfd16e-2e6c-4e0e-a966-d7093ae5e0bc"),
                            Count = 3,
                            HotelId = new Guid("390d22d9-89cb-4b5b-8ed2-db63c20c1fe0"),
                            Price = 57m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a6609dd8-3ff9-4002-b620-0f71484b5761"),
                            Count = 2,
                            HotelId = new Guid("384e7d47-f9e4-432e-9036-34d6da8152eb"),
                            Price = 140m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3b1ce55d-3252-468f-8930-aa73eb279653"),
                            Count = 3,
                            HotelId = new Guid("384e7d47-f9e4-432e-9036-34d6da8152eb"),
                            Price = 181m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("41d23654-6590-4ee9-9452-dfd3ee433cf6"),
                            Count = 1,
                            HotelId = new Guid("384e7d47-f9e4-432e-9036-34d6da8152eb"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c5339276-939b-4814-a8a5-b605c468ef42"),
                            Count = 2,
                            HotelId = new Guid("384e7d47-f9e4-432e-9036-34d6da8152eb"),
                            Price = 226m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("44321137-fda7-4716-b023-8ada0aadd844"),
                            Count = 1,
                            HotelId = new Guid("4d41a2f3-e79d-47f6-93e3-31990462b67c"),
                            Price = 159m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ecee996b-0938-464f-a0a8-1c0047cfc8ac"),
                            Count = 2,
                            HotelId = new Guid("4d41a2f3-e79d-47f6-93e3-31990462b67c"),
                            Price = 203m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ced6af0b-0dbd-4c93-87a0-944dfc01510f"),
                            Count = 1,
                            HotelId = new Guid("4d41a2f3-e79d-47f6-93e3-31990462b67c"),
                            Price = 222m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f33b9605-b0e9-4c63-a899-dc004c7c516f"),
                            Count = 3,
                            HotelId = new Guid("4d41a2f3-e79d-47f6-93e3-31990462b67c"),
                            Price = 50m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e00850ba-ad63-4878-b2a9-292241d241c3"),
                            Count = 2,
                            HotelId = new Guid("fb56e927-a622-46fd-82a7-32bb2c3e30b2"),
                            Price = 147m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("a312fab8-8d93-4287-96f4-44965d4c706d"),
                            Count = 1,
                            HotelId = new Guid("fb56e927-a622-46fd-82a7-32bb2c3e30b2"),
                            Price = 127m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ef7ade87-faa9-4c99-a0be-aec3db3d6a6f"),
                            Count = 2,
                            HotelId = new Guid("fb56e927-a622-46fd-82a7-32bb2c3e30b2"),
                            Price = 204m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("20b61173-6008-48cf-925d-e4bc30c193fe"),
                            Count = 1,
                            HotelId = new Guid("fb56e927-a622-46fd-82a7-32bb2c3e30b2"),
                            Price = 247m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("15d09c0a-bf6e-48bc-a6e1-12b604a81cb3"),
                            Count = 3,
                            HotelId = new Guid("91492bb1-767f-4b58-829f-e4475a314d1a"),
                            Price = 168m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("dfda7488-9c3d-4a7d-8911-84f94f9f753e"),
                            Count = 1,
                            HotelId = new Guid("91492bb1-767f-4b58-829f-e4475a314d1a"),
                            Price = 241m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("836d9cbd-611d-4468-97b2-002079a3e7f0"),
                            Count = 3,
                            HotelId = new Guid("91492bb1-767f-4b58-829f-e4475a314d1a"),
                            Price = 185m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("751994d4-641e-4ae9-8bd7-abee30eedd29"),
                            Count = 1,
                            HotelId = new Guid("91492bb1-767f-4b58-829f-e4475a314d1a"),
                            Price = 215m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e499214d-0065-46b1-9210-6ec5d01119c1"),
                            Count = 1,
                            HotelId = new Guid("832de1a7-b9d9-4bbc-8a4b-c9f68cb0e6fb"),
                            Price = 50m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("69b5b886-7003-46b1-a073-c9942d993c89"),
                            Count = 3,
                            HotelId = new Guid("832de1a7-b9d9-4bbc-8a4b-c9f68cb0e6fb"),
                            Price = 235m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("fe5c2037-8fa9-4554-b5e7-afd79657e4e0"),
                            Count = 2,
                            HotelId = new Guid("832de1a7-b9d9-4bbc-8a4b-c9f68cb0e6fb"),
                            Price = 243m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c197c5a7-5d77-4769-8e95-789eaaf1c993"),
                            Count = 3,
                            HotelId = new Guid("832de1a7-b9d9-4bbc-8a4b-c9f68cb0e6fb"),
                            Price = 73m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6dfe53b7-4e6b-48b5-bcd6-ad2ffa1d661a"),
                            Count = 3,
                            HotelId = new Guid("c0a97197-ac51-41ab-a63b-340a31f8d25a"),
                            Price = 229m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c966fa97-55a8-4aca-978e-65bbd61d4eab"),
                            Count = 3,
                            HotelId = new Guid("c0a97197-ac51-41ab-a63b-340a31f8d25a"),
                            Price = 153m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ecf06b6b-c3e8-48a0-be6e-dfe9bc6e44e5"),
                            Count = 3,
                            HotelId = new Guid("c0a97197-ac51-41ab-a63b-340a31f8d25a"),
                            Price = 87m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("0c84ce5a-45be-4560-b7c5-db12e3259527"),
                            Count = 1,
                            HotelId = new Guid("c0a97197-ac51-41ab-a63b-340a31f8d25a"),
                            Price = 59m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("51db99ad-652d-4829-b36b-01679060b498"),
                            Count = 1,
                            HotelId = new Guid("392a2517-d760-4f0c-bf1b-3f76ed2a5b5d"),
                            Price = 171m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2cf8fb5f-5cb5-4081-9705-ac620652537f"),
                            Count = 2,
                            HotelId = new Guid("392a2517-d760-4f0c-bf1b-3f76ed2a5b5d"),
                            Price = 87m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("67d5d998-c1a5-4fa9-8e06-c5169ecce3b2"),
                            Count = 2,
                            HotelId = new Guid("392a2517-d760-4f0c-bf1b-3f76ed2a5b5d"),
                            Price = 159m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("57781933-1902-4059-abd2-39062bd8a812"),
                            Count = 2,
                            HotelId = new Guid("392a2517-d760-4f0c-bf1b-3f76ed2a5b5d"),
                            Price = 143m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("174248b0-58c6-4e71-b9d1-a80d6dd56315"),
                            Count = 2,
                            HotelId = new Guid("33c07c58-128d-4230-b102-2d75ec3f5c6c"),
                            Price = 171m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("87567091-319d-4837-81d8-8d79f767ffd0"),
                            Count = 2,
                            HotelId = new Guid("33c07c58-128d-4230-b102-2d75ec3f5c6c"),
                            Price = 148m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("db96975b-8ea6-40e9-b10e-db15ca6187f9"),
                            Count = 2,
                            HotelId = new Guid("33c07c58-128d-4230-b102-2d75ec3f5c6c"),
                            Price = 91m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e969af57-73b4-4908-9dcc-479bd868daee"),
                            Count = 1,
                            HotelId = new Guid("33c07c58-128d-4230-b102-2d75ec3f5c6c"),
                            Price = 172m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("caa23a2b-7ce5-4444-a6c1-098a43e8b7d1"),
                            Count = 3,
                            HotelId = new Guid("f869ad97-26c7-45e5-b83c-85723f9867bf"),
                            Price = 70m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d96184b7-97f2-4855-a541-1ef468850857"),
                            Count = 1,
                            HotelId = new Guid("f869ad97-26c7-45e5-b83c-85723f9867bf"),
                            Price = 92m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("dbe9d969-4c1d-48d9-8159-114b38e9d741"),
                            Count = 2,
                            HotelId = new Guid("f869ad97-26c7-45e5-b83c-85723f9867bf"),
                            Price = 206m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f36a32fe-170b-457a-93ce-c78382f8b5cb"),
                            Count = 3,
                            HotelId = new Guid("f869ad97-26c7-45e5-b83c-85723f9867bf"),
                            Price = 175m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("88645b4d-5276-4d7a-8715-9c6fd1979060"),
                            Count = 1,
                            HotelId = new Guid("9699fea0-c651-4a40-828c-1b3e304c3edc"),
                            Price = 92m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f98a7bd5-1b68-4d96-a39c-bb2735961e3b"),
                            Count = 2,
                            HotelId = new Guid("9699fea0-c651-4a40-828c-1b3e304c3edc"),
                            Price = 199m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("3119c03c-010c-4e92-bab8-6f34f20186cd"),
                            Count = 3,
                            HotelId = new Guid("9699fea0-c651-4a40-828c-1b3e304c3edc"),
                            Price = 141m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4252ce03-14d6-4c8d-8a22-53a6bcec53cc"),
                            Count = 1,
                            HotelId = new Guid("9699fea0-c651-4a40-828c-1b3e304c3edc"),
                            Price = 140m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ccd1ba57-fd75-4be2-a61c-a0d8354510d9"),
                            Count = 1,
                            HotelId = new Guid("b5dfb131-8042-4bec-ac0e-adc3a18d75d0"),
                            Price = 221m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("68962468-9e2f-42cd-80b2-0569900b296e"),
                            Count = 2,
                            HotelId = new Guid("b5dfb131-8042-4bec-ac0e-adc3a18d75d0"),
                            Price = 236m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("798c8989-971e-4744-8abc-2f836db0dcca"),
                            Count = 3,
                            HotelId = new Guid("b5dfb131-8042-4bec-ac0e-adc3a18d75d0"),
                            Price = 226m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9bad65ec-6c07-465c-891e-7cc341dd29d5"),
                            Count = 1,
                            HotelId = new Guid("b5dfb131-8042-4bec-ac0e-adc3a18d75d0"),
                            Price = 106m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("516261f7-4a2d-4b70-965f-056286aaa289"),
                            Count = 3,
                            HotelId = new Guid("fa68ad5b-ffbe-48ae-9f93-8fa94bf7226c"),
                            Price = 230m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c8871faa-b4e1-4879-9d1b-6fb33485a16d"),
                            Count = 2,
                            HotelId = new Guid("fa68ad5b-ffbe-48ae-9f93-8fa94bf7226c"),
                            Price = 159m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6611ae3c-51cb-42bb-8f9b-a92dda284823"),
                            Count = 3,
                            HotelId = new Guid("fa68ad5b-ffbe-48ae-9f93-8fa94bf7226c"),
                            Price = 98m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("71b1b9d4-87f9-4978-aee0-62581dd04ab8"),
                            Count = 3,
                            HotelId = new Guid("fa68ad5b-ffbe-48ae-9f93-8fa94bf7226c"),
                            Price = 85m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("8aa504e7-7953-4544-8edb-851a67255a69"),
                            Count = 2,
                            HotelId = new Guid("12b63b13-0780-4dd0-bf96-564594543b79"),
                            Price = 98m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("792726b0-b2cb-4ae9-bd77-42d47183497e"),
                            Count = 3,
                            HotelId = new Guid("12b63b13-0780-4dd0-bf96-564594543b79"),
                            Price = 135m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("0c1fed65-29b3-4843-af11-61a453c11fd6"),
                            Count = 3,
                            HotelId = new Guid("12b63b13-0780-4dd0-bf96-564594543b79"),
                            Price = 211m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ed2c6011-158f-48d5-a158-5d0a3eaba2b3"),
                            Count = 3,
                            HotelId = new Guid("12b63b13-0780-4dd0-bf96-564594543b79"),
                            Price = 91m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("007e116e-5e14-44b2-a901-f95b9305214b"),
                            Count = 3,
                            HotelId = new Guid("ca7c8aaf-de51-46e6-95f7-f7147440b528"),
                            Price = 117m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("7fdba6f3-da59-449c-9d74-aa0a5828ef6a"),
                            Count = 2,
                            HotelId = new Guid("ca7c8aaf-de51-46e6-95f7-f7147440b528"),
                            Price = 178m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c1fb9b9d-370b-49bf-a190-f06b8b13f03b"),
                            Count = 3,
                            HotelId = new Guid("ca7c8aaf-de51-46e6-95f7-f7147440b528"),
                            Price = 222m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1918ae9f-49c5-4f80-8e5f-f811ea8a83fd"),
                            Count = 3,
                            HotelId = new Guid("ca7c8aaf-de51-46e6-95f7-f7147440b528"),
                            Price = 150m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b214b9af-3a88-4d13-a160-d01edfdb70f6"),
                            Count = 3,
                            HotelId = new Guid("83ce943a-f3df-4fb5-9c37-a659b5afc2c8"),
                            Price = 57m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("57826ac0-eea7-4c6a-ac1b-d0df116fe8d5"),
                            Count = 3,
                            HotelId = new Guid("83ce943a-f3df-4fb5-9c37-a659b5afc2c8"),
                            Price = 109m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b52de355-1c63-4135-a8b3-11f2df71c7e3"),
                            Count = 1,
                            HotelId = new Guid("83ce943a-f3df-4fb5-9c37-a659b5afc2c8"),
                            Price = 80m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f85dce40-9172-4ce5-a4d4-a9069c77ac2a"),
                            Count = 1,
                            HotelId = new Guid("83ce943a-f3df-4fb5-9c37-a659b5afc2c8"),
                            Price = 164m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3b3906cf-e16a-4a4b-b393-2b6b47686e40"),
                            Count = 2,
                            HotelId = new Guid("fd285982-c0cf-4a0c-b248-0b194c17210c"),
                            Price = 219m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("67bbf2e7-a3c0-4b08-a1b8-4ed656494b3a"),
                            Count = 3,
                            HotelId = new Guid("fd285982-c0cf-4a0c-b248-0b194c17210c"),
                            Price = 119m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("fee5db84-7006-494a-82a3-f0ca1b9384dd"),
                            Count = 3,
                            HotelId = new Guid("fd285982-c0cf-4a0c-b248-0b194c17210c"),
                            Price = 174m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("73dd3d70-98a4-4ba4-b996-61728bb04747"),
                            Count = 3,
                            HotelId = new Guid("fd285982-c0cf-4a0c-b248-0b194c17210c"),
                            Price = 127m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("14a92577-fa68-4479-a05c-4e17151c31b4"),
                            Count = 2,
                            HotelId = new Guid("c94df083-fc2a-4695-8493-f02af5db384b"),
                            Price = 159m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4d5cd011-0823-41c1-b401-fdf7006aaf0f"),
                            Count = 3,
                            HotelId = new Guid("c94df083-fc2a-4695-8493-f02af5db384b"),
                            Price = 153m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("918a5b35-a35b-45c7-9c6c-0f538735ad68"),
                            Count = 3,
                            HotelId = new Guid("c94df083-fc2a-4695-8493-f02af5db384b"),
                            Price = 173m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("066af1ee-3733-4286-aea9-4d268b25a9eb"),
                            Count = 1,
                            HotelId = new Guid("c94df083-fc2a-4695-8493-f02af5db384b"),
                            Price = 172m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("2c5d580a-b6fe-4620-99c8-0b53fcfdcad6"),
                            Count = 3,
                            HotelId = new Guid("76a510f4-a1ee-40e7-8236-7b58e0772d98"),
                            Price = 55m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("99ea04bb-bc21-41aa-bbdb-b034f62012e4"),
                            Count = 2,
                            HotelId = new Guid("76a510f4-a1ee-40e7-8236-7b58e0772d98"),
                            Price = 193m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("73b4b533-f7c1-4869-b23d-9c379be0f30d"),
                            Count = 2,
                            HotelId = new Guid("76a510f4-a1ee-40e7-8236-7b58e0772d98"),
                            Price = 130m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("6ce365ec-de05-4f5b-bc14-3ac652664fca"),
                            Count = 1,
                            HotelId = new Guid("76a510f4-a1ee-40e7-8236-7b58e0772d98"),
                            Price = 240m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c6a5250d-afc7-45f6-ad10-d6368066fe70"),
                            Count = 1,
                            HotelId = new Guid("887a924c-5946-4819-b49c-70a717b9ff2f"),
                            Price = 139m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e009f6e7-4ab0-4cb1-8b44-4c9462c3cb84"),
                            Count = 2,
                            HotelId = new Guid("887a924c-5946-4819-b49c-70a717b9ff2f"),
                            Price = 140m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("aeb30c86-5233-4278-948f-e1097a217b83"),
                            Count = 1,
                            HotelId = new Guid("887a924c-5946-4819-b49c-70a717b9ff2f"),
                            Price = 250m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4ac29a10-7c62-4f9b-bd02-6b4788883e77"),
                            Count = 2,
                            HotelId = new Guid("887a924c-5946-4819-b49c-70a717b9ff2f"),
                            Price = 51m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("953cfcf3-911b-48fd-bba7-ac601a35c926"),
                            Count = 3,
                            HotelId = new Guid("bbf5e021-266d-4020-8279-b6df7f250f53"),
                            Price = 63m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("faeae1a4-a512-4684-986b-ad965d19ec6c"),
                            Count = 2,
                            HotelId = new Guid("bbf5e021-266d-4020-8279-b6df7f250f53"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("5542537c-39fa-424b-9d9b-e92e05a8019a"),
                            Count = 1,
                            HotelId = new Guid("bbf5e021-266d-4020-8279-b6df7f250f53"),
                            Price = 116m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d243bcf1-c3d2-4f34-889b-053fdeba94b6"),
                            Count = 1,
                            HotelId = new Guid("bbf5e021-266d-4020-8279-b6df7f250f53"),
                            Price = 191m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("495cd99b-6d24-4ecb-96f6-6c6a0d5a13a6"),
                            Count = 1,
                            HotelId = new Guid("984962a4-b362-4e3b-a8c3-5124c19ed106"),
                            Price = 249m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8f1e3364-f11c-4d59-a2a6-e700b58cbb3e"),
                            Count = 2,
                            HotelId = new Guid("984962a4-b362-4e3b-a8c3-5124c19ed106"),
                            Price = 53m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d586051a-6700-4f8c-8ad9-49c76db8fe4e"),
                            Count = 2,
                            HotelId = new Guid("984962a4-b362-4e3b-a8c3-5124c19ed106"),
                            Price = 237m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c3e79e25-4d71-4648-bb6d-c7aa1b912e5f"),
                            Count = 3,
                            HotelId = new Guid("984962a4-b362-4e3b-a8c3-5124c19ed106"),
                            Price = 52m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c11520f6-8ef1-4f5b-b1b2-870a73622419"),
                            Count = 3,
                            HotelId = new Guid("1eba02c2-00f8-4190-a118-d4970c7de667"),
                            Price = 236m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("56115bea-f0b9-440e-b245-a543fa79da02"),
                            Count = 1,
                            HotelId = new Guid("1eba02c2-00f8-4190-a118-d4970c7de667"),
                            Price = 97m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("53b9c8e0-1a59-4d88-bece-76bad7b0f6f3"),
                            Count = 1,
                            HotelId = new Guid("1eba02c2-00f8-4190-a118-d4970c7de667"),
                            Price = 65m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2f180121-5960-4020-9655-297b289a2de4"),
                            Count = 1,
                            HotelId = new Guid("1eba02c2-00f8-4190-a118-d4970c7de667"),
                            Price = 208m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f9b3bec4-6817-47a3-ab80-cd6ffa399bb5"),
                            Count = 1,
                            HotelId = new Guid("57b599b2-ea69-400c-80b8-f2222e2cf10c"),
                            Price = 163m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("b7cc4f19-ccb6-4a0f-95f5-33733d13596c"),
                            Count = 3,
                            HotelId = new Guid("57b599b2-ea69-400c-80b8-f2222e2cf10c"),
                            Price = 250m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a40f8917-2338-444f-bb53-867e04022003"),
                            Count = 3,
                            HotelId = new Guid("57b599b2-ea69-400c-80b8-f2222e2cf10c"),
                            Price = 134m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d684a8ba-2566-4aea-868f-bfb74631b96e"),
                            Count = 3,
                            HotelId = new Guid("57b599b2-ea69-400c-80b8-f2222e2cf10c"),
                            Price = 81m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("78d34f6a-3ace-4ed5-84b0-12db85ec8d6f"),
                            Count = 1,
                            HotelId = new Guid("c5fcc3f1-ae51-4f8d-93a3-3cbceadd8029"),
                            Price = 158m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("bdece263-a952-4bac-b377-3309911e4bdf"),
                            Count = 2,
                            HotelId = new Guid("c5fcc3f1-ae51-4f8d-93a3-3cbceadd8029"),
                            Price = 177m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4798c241-b744-4a56-b436-9b5bd5a6f71c"),
                            Count = 2,
                            HotelId = new Guid("c5fcc3f1-ae51-4f8d-93a3-3cbceadd8029"),
                            Price = 100m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1cbf812e-60b5-4858-b89a-aaa8f289f29a"),
                            Count = 1,
                            HotelId = new Guid("c5fcc3f1-ae51-4f8d-93a3-3cbceadd8029"),
                            Price = 104m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f72a153a-2cc1-4170-82a8-ea5c5ed2830e"),
                            Count = 1,
                            HotelId = new Guid("9e0b4c5e-37d8-45cd-a054-e0287686b5ed"),
                            Price = 77m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fcfc6d06-90c1-44a7-b8ab-26b2e0ae2130"),
                            Count = 2,
                            HotelId = new Guid("9e0b4c5e-37d8-45cd-a054-e0287686b5ed"),
                            Price = 248m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c05f6931-f618-4506-b209-b2b698c930e9"),
                            Count = 1,
                            HotelId = new Guid("9e0b4c5e-37d8-45cd-a054-e0287686b5ed"),
                            Price = 215m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c273dd33-e0dd-4157-b3b2-80e097abbdab"),
                            Count = 1,
                            HotelId = new Guid("9e0b4c5e-37d8-45cd-a054-e0287686b5ed"),
                            Price = 248m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("cb6f4e7f-21c4-422c-a4d9-6de2ec21eb89"),
                            Count = 3,
                            HotelId = new Guid("593235a6-71b4-4f1b-814f-8338e22fe404"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f19f6e6f-3d82-4e5c-874c-48e27e052a7b"),
                            Count = 2,
                            HotelId = new Guid("593235a6-71b4-4f1b-814f-8338e22fe404"),
                            Price = 53m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("e00f1d8d-5fab-4513-bd46-9de40e1f9121"),
                            Count = 3,
                            HotelId = new Guid("593235a6-71b4-4f1b-814f-8338e22fe404"),
                            Price = 192m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("2e156c3f-477d-4925-be76-ed961b63aa0c"),
                            Count = 2,
                            HotelId = new Guid("593235a6-71b4-4f1b-814f-8338e22fe404"),
                            Price = 120m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("200ec92a-e88a-4d24-b23b-7a4085e6eb20"),
                            Count = 2,
                            HotelId = new Guid("6bc5772a-43c7-4d16-b56a-2fd0f5576681"),
                            Price = 205m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8e1dfed5-ac9d-4c8f-98cf-74a915248e6e"),
                            Count = 1,
                            HotelId = new Guid("6bc5772a-43c7-4d16-b56a-2fd0f5576681"),
                            Price = 241m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("54a74870-d544-46f1-9b83-eaa2261ea07b"),
                            Count = 2,
                            HotelId = new Guid("6bc5772a-43c7-4d16-b56a-2fd0f5576681"),
                            Price = 92m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4c948705-55a8-49ab-b9fa-e21a7c570b1c"),
                            Count = 3,
                            HotelId = new Guid("6bc5772a-43c7-4d16-b56a-2fd0f5576681"),
                            Price = 52m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c1dff838-695b-48b5-9f89-65c0e4e58f7d"),
                            Count = 2,
                            HotelId = new Guid("44933f93-2830-46bd-bb3f-90a47a8dd8d3"),
                            Price = 51m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("74b80e8c-080f-4b4e-9d56-08a6a0636359"),
                            Count = 2,
                            HotelId = new Guid("44933f93-2830-46bd-bb3f-90a47a8dd8d3"),
                            Price = 137m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("79e30df7-fd01-42d4-929a-9ba59c1d7a2a"),
                            Count = 2,
                            HotelId = new Guid("44933f93-2830-46bd-bb3f-90a47a8dd8d3"),
                            Price = 222m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9e2de49c-84e3-4deb-a2aa-10fc7080c6f3"),
                            Count = 2,
                            HotelId = new Guid("44933f93-2830-46bd-bb3f-90a47a8dd8d3"),
                            Price = 77m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a9af942a-68a5-4a93-88dd-312be3396bc3"),
                            Count = 2,
                            HotelId = new Guid("61b21151-7cf1-4482-a3dc-37f169d554e1"),
                            Price = 161m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("512200cf-c63e-4836-bbfd-981eff207c2f"),
                            Count = 1,
                            HotelId = new Guid("61b21151-7cf1-4482-a3dc-37f169d554e1"),
                            Price = 99m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b2a3ad0e-e8e0-4153-9b80-09d79ca8ee5a"),
                            Count = 2,
                            HotelId = new Guid("61b21151-7cf1-4482-a3dc-37f169d554e1"),
                            Price = 139m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("eb5d5452-9889-46d0-8770-957ef9c11613"),
                            Count = 1,
                            HotelId = new Guid("61b21151-7cf1-4482-a3dc-37f169d554e1"),
                            Price = 55m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3829f8a2-08bf-4e99-b497-0657a505e5bc"),
                            Count = 3,
                            HotelId = new Guid("318a37a9-8132-4cb5-bab1-df114dafabf4"),
                            Price = 65m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("e896168c-9030-4edd-b063-d171eb999d09"),
                            Count = 1,
                            HotelId = new Guid("318a37a9-8132-4cb5-bab1-df114dafabf4"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("713dcc4f-adc2-46f2-904e-150f8ffc712f"),
                            Count = 3,
                            HotelId = new Guid("318a37a9-8132-4cb5-bab1-df114dafabf4"),
                            Price = 55m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("80930220-b37d-432f-9743-6e801c23b524"),
                            Count = 1,
                            HotelId = new Guid("318a37a9-8132-4cb5-bab1-df114dafabf4"),
                            Price = 228m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3b45f947-b7d1-4371-87bb-81a07f293c5a"),
                            Count = 3,
                            HotelId = new Guid("b28d50e4-41b0-403b-af83-5a0c5f733173"),
                            Price = 204m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8efc2198-7829-4d5e-a14a-39a7c7499a4a"),
                            Count = 3,
                            HotelId = new Guid("b28d50e4-41b0-403b-af83-5a0c5f733173"),
                            Price = 229m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("92a55e94-13fa-49cb-8dce-333bc539dfbd"),
                            Count = 2,
                            HotelId = new Guid("b28d50e4-41b0-403b-af83-5a0c5f733173"),
                            Price = 168m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("95fa4e01-26db-4bdc-b645-fe0a990ba9e0"),
                            Count = 3,
                            HotelId = new Guid("b28d50e4-41b0-403b-af83-5a0c5f733173"),
                            Price = 194m,
                            Size = 5
                        });
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomsReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Discounts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.HasOne("hotelservice.Models.Room", null)
                        .WithMany("Bookings")
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
