// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hotelservice.Models;

#nullable disable

namespace hotelservice.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20240606110400_RemoveEndFieldFromDiscount")]
    partial class RemoveEndFieldFromDiscount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FoodPricePerPerson")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e69488ef-5468-4301-ba52-0c0248480911"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 83m,
                            Name = "Pinea Resort & Spa",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("95a4b949-df50-4c39-99d8-836cbe7f0ac3"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 34m,
                            Name = "Diamma Resort",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("6a6e01aa-c848-47d4-bfb1-cede6abe8a14"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 31m,
                            Name = "Bonita Luxury Hotel",
                            Street = "Rruga Abdyl Frasheri"
                        },
                        new
                        {
                            Id = new Guid("6965f8e0-b3b3-43da-87b4-beca8798d1f3"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 90m,
                            Name = "Monte Carlo Vlora",
                            Street = "Rruga 28 Nentori"
                        },
                        new
                        {
                            Id = new Guid("3a736cd3-b233-436c-911c-7073b4befd00"),
                            City = "Vlora",
                            Country = "albania",
                            FoodPricePerPerson = 99m,
                            Name = "MonteCarlo Lungomare",
                            Street = "Rruga e Kavajes"
                        },
                        new
                        {
                            Id = new Guid("d7426795-c33a-4a80-887b-5fdb61e85189"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 94m,
                            Name = "Mel Holidays",
                            Street = "Bulevardi Bajram Curri"
                        },
                        new
                        {
                            Id = new Guid("5a9fa78e-b2d1-4cde-955c-1571b9a626f4"),
                            City = "Durres",
                            Country = "albania",
                            FoodPricePerPerson = 74m,
                            Name = "Casa Durres",
                            Street = "Rruga e Dibres"
                        },
                        new
                        {
                            Id = new Guid("57a2fb51-16c7-4473-9eb9-f74be1117c10"),
                            City = "Chania",
                            Country = "grecja",
                            FoodPricePerPerson = 91m,
                            Name = "Rethymno Mare Water Park",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("a6150683-f3f8-4578-ae91-74a2816b8f1c"),
                            City = "Peloponez",
                            Country = "grecja",
                            FoodPricePerPerson = 43m,
                            Name = "Aldemar Olympian Village",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("1d2d61f2-2cbb-459c-be2d-1f8ed260a82f"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 56m,
                            Name = "Studia Katerina",
                            Street = "Leoforos Vasilissis Sofias"
                        },
                        new
                        {
                            Id = new Guid("9534c589-acd0-49e8-bb4e-449e58445b2e"),
                            City = "Heraklion",
                            Country = "grecja",
                            FoodPricePerPerson = 74m,
                            Name = "Irini Studios",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("35f98b61-1d9e-4a7a-b9b3-1c8b88372c9b"),
                            City = "Nero",
                            Country = "grecja",
                            FoodPricePerPerson = 110m,
                            Name = "Studia Maria",
                            Street = "Leoforos Alexandras"
                        },
                        new
                        {
                            Id = new Guid("2b78b471-830c-4962-9528-1138ea6bbcd8"),
                            City = "Olimpijska",
                            Country = "grecja",
                            FoodPricePerPerson = 31m,
                            Name = "Dias Apartments",
                            Street = "Plateia Syntagmatos"
                        },
                        new
                        {
                            Id = new Guid("4eb84047-b94a-469c-8f86-88592dab054e"),
                            City = "Marmaris",
                            Country = "turcja",
                            FoodPricePerPerson = 109m,
                            Name = "Turunc Resort",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("0737c9f6-d5d2-4670-b36a-676cf05162e7"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 111m,
                            Name = "Andriake Beach Club Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("60c22255-ba18-41dd-a0ef-87dd77035055"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 114m,
                            Name = "Kimeros Park Holiday Village",
                            Street = "Bağdat Caddesi"
                        },
                        new
                        {
                            Id = new Guid("5522d316-af4b-43ab-8700-3dd77a1dc2be"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 35m,
                            Name = "Kleopatra Micador",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("ef28f7ba-5f04-49a7-aa7d-846c79471671"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 50m,
                            Name = "Melissa",
                            Street = "Halaskargazi Caddesi"
                        },
                        new
                        {
                            Id = new Guid("60a51295-7af8-47ec-8a4e-4f6c4feeb74c"),
                            City = "Turecka",
                            Country = "turcja",
                            FoodPricePerPerson = 107m,
                            Name = "Kolibri Hotel",
                            Street = "Atatürk Caddesi"
                        },
                        new
                        {
                            Id = new Guid("22700625-15d0-4773-8024-09759cbd76f4"),
                            City = "Almeria",
                            Country = "hiszpania",
                            FoodPricePerPerson = 38m,
                            Name = "Evenia Zoraida Beach Resort",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("b23a15ff-7161-4d3f-9da5-ddc10d69690e"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 96m,
                            Name = "Evenia Olympic Park",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("ac76333f-1a54-4bc7-a615-04121417b975"),
                            City = "Luz",
                            Country = "hiszpania",
                            FoodPricePerPerson = 94m,
                            Name = "Estival Islantilla",
                            Street = "Calle Mayor"
                        },
                        new
                        {
                            Id = new Guid("b28b03ba-9bc3-4e76-aa25-8842d9da7125"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 37m,
                            Name = "Cartago Nova by Alegria",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("a9463ad4-4c8e-4169-ac7d-888e4da65cdf"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 67m,
                            Name = "Catalonia",
                            Street = "Calle de Alcalá"
                        },
                        new
                        {
                            Id = new Guid("2b0499aa-f505-4f07-96db-1beac88a40a5"),
                            City = "Maresme",
                            Country = "hiszpania",
                            FoodPricePerPerson = 106m,
                            Name = "Reymar Playa",
                            Street = "Paseo del Prado"
                        },
                        new
                        {
                            Id = new Guid("73950b5b-00a3-462b-8fe8-1ab5975538d4"),
                            City = "Brava",
                            Country = "hiszpania",
                            FoodPricePerPerson = 77m,
                            Name = "GHT Oasis Park & Spa",
                            Street = "Gran Vía"
                        },
                        new
                        {
                            Id = new Guid("fef1b7d4-5330-46d9-9497-6c8192fb731c"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 79m,
                            Name = "San Domenico",
                            Street = "Via del Corso"
                        },
                        new
                        {
                            Id = new Guid("f6721867-bada-4412-a649-efe2fea10ba8"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 47m,
                            Name = "Baia di Zambrone",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("240c7544-7f24-46db-9cf4-b3a7077f3219"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 93m,
                            Name = "Rada Siri",
                            Street = "Via Veneto"
                        },
                        new
                        {
                            Id = new Guid("7df7ce44-24e8-4cba-9848-5f872b24c0e0"),
                            City = "Kalabria",
                            Country = "wlochy",
                            FoodPricePerPerson = 81m,
                            Name = "Hotel Orizzonte Blu",
                            Street = "Via Nazionale"
                        },
                        new
                        {
                            Id = new Guid("df03a41e-617c-4637-be81-426f59520ff2"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 116m,
                            Name = "Gradac",
                            Street = "Kapucinska ulica"
                        },
                        new
                        {
                            Id = new Guid("feed0ab7-f131-4481-91e0-60dba2702c8c"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 31m,
                            Name = "Villa Penava",
                            Street = "Trg bana Josipa Jelačića"
                        },
                        new
                        {
                            Id = new Guid("14d17a0c-0430-4566-871f-892896a088bb"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 42m,
                            Name = "Apartamenty Omiś",
                            Street = "Vukovarska ulica"
                        },
                        new
                        {
                            Id = new Guid("e742c5b7-6cfd-4e8b-b50f-2df1ce562ab3"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 88m,
                            Name = "Nano",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("a34b791f-8993-4377-9177-0cd9a93330b9"),
                            City = "Riwiera",
                            Country = "chorwacja",
                            FoodPricePerPerson = 83m,
                            Name = "Apartamenty Makarska",
                            Street = "Maksimirska ulica"
                        },
                        new
                        {
                            Id = new Guid("f18ad2a3-87ab-4563-8a4e-62501a24ba63"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 97m,
                            Name = "Marina Resort Port Ghalib",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("df518aaf-3e1e-40cb-b5e9-d40da5debb0a"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 76m,
                            Name = "Barcelo Tiran Sharm Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("8df68a40-c7a2-4d3b-9956-1a7c4fcf5be3"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 74m,
                            Name = "Old Vic Resort Sharm",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("092ce8d5-6ec0-46ef-baa7-025b0c6a0808"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 33m,
                            Name = "Marina Lodge Port Ghalib",
                            Street = "Sharia Ramsis"
                        },
                        new
                        {
                            Id = new Guid("145aa16e-eeac-45bd-a513-c1ee1423e2c8"),
                            City = "Sheikh",
                            Country = "egipt",
                            FoodPricePerPerson = 116m,
                            Name = "Falcon Naama Star",
                            Street = "Sharia Salah Salem"
                        },
                        new
                        {
                            Id = new Guid("e057c1d0-789e-44ee-989c-8f393367970a"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 80m,
                            Name = "Protels Crystal Beach Resort",
                            Street = "Sharia Tahrir"
                        },
                        new
                        {
                            Id = new Guid("8e7d534f-b5ef-45a0-aa20-f4955f296e6b"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 89m,
                            Name = "MG Alexander The Great",
                            Street = "Sharia Gamal Abdel Nasser"
                        },
                        new
                        {
                            Id = new Guid("72398cd6-f009-48f7-b6c4-0d21cc667043"),
                            City = "Alam",
                            Country = "egipt",
                            FoodPricePerPerson = 83m,
                            Name = "Bliss Nada Beach Resort",
                            Street = "Sharia Tahrir"
                        });
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e33b455-c96e-4328-8c54-6b7baf00adec"),
                            Count = 3,
                            HotelId = new Guid("e69488ef-5468-4301-ba52-0c0248480911"),
                            Price = 119m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9f6e4495-314d-41e5-a59c-02c036494e26"),
                            Count = 2,
                            HotelId = new Guid("e69488ef-5468-4301-ba52-0c0248480911"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("0b5978f3-45f7-40cc-8ef1-1463ace598aa"),
                            Count = 2,
                            HotelId = new Guid("e69488ef-5468-4301-ba52-0c0248480911"),
                            Price = 123m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("a7b64b77-aabb-41a3-ab0d-a2424a84202c"),
                            Count = 2,
                            HotelId = new Guid("e69488ef-5468-4301-ba52-0c0248480911"),
                            Price = 215m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("c9413b76-ef6f-4c5c-8291-873c0a724e6e"),
                            Count = 2,
                            HotelId = new Guid("95a4b949-df50-4c39-99d8-836cbe7f0ac3"),
                            Price = 145m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f258af04-74df-43fb-bf09-655d4d4d084e"),
                            Count = 2,
                            HotelId = new Guid("95a4b949-df50-4c39-99d8-836cbe7f0ac3"),
                            Price = 138m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("31260f95-2833-448c-8381-47723e1caeb7"),
                            Count = 3,
                            HotelId = new Guid("95a4b949-df50-4c39-99d8-836cbe7f0ac3"),
                            Price = 74m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1c9b2701-535b-43e4-936d-8ff9980c00ed"),
                            Count = 1,
                            HotelId = new Guid("95a4b949-df50-4c39-99d8-836cbe7f0ac3"),
                            Price = 205m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("a0d231f6-a5ff-459d-b0b7-a17cafa01b89"),
                            Count = 2,
                            HotelId = new Guid("6a6e01aa-c848-47d4-bfb1-cede6abe8a14"),
                            Price = 186m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1b12e675-6c5d-4db6-8e9b-18e49baeb5d9"),
                            Count = 3,
                            HotelId = new Guid("6a6e01aa-c848-47d4-bfb1-cede6abe8a14"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("05329b55-c053-4c65-b67c-84c097d6ddcb"),
                            Count = 1,
                            HotelId = new Guid("6a6e01aa-c848-47d4-bfb1-cede6abe8a14"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("80f723c9-b6b0-40e0-849b-3ed9873a8135"),
                            Count = 1,
                            HotelId = new Guid("6a6e01aa-c848-47d4-bfb1-cede6abe8a14"),
                            Price = 69m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("72d34663-67c2-4c8c-86cd-c090a01ceed8"),
                            Count = 1,
                            HotelId = new Guid("6965f8e0-b3b3-43da-87b4-beca8798d1f3"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fb698f0a-6bb9-43ce-a82b-4e11cbd0f114"),
                            Count = 3,
                            HotelId = new Guid("6965f8e0-b3b3-43da-87b4-beca8798d1f3"),
                            Price = 147m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1112cb94-3b41-40ec-93c3-3305eaad4367"),
                            Count = 2,
                            HotelId = new Guid("6965f8e0-b3b3-43da-87b4-beca8798d1f3"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e58b02e4-6bf5-45fb-bcfa-f9a1906b56e7"),
                            Count = 3,
                            HotelId = new Guid("6965f8e0-b3b3-43da-87b4-beca8798d1f3"),
                            Price = 110m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("d4b67c2c-28d9-4737-a308-96e06acbf765"),
                            Count = 3,
                            HotelId = new Guid("3a736cd3-b233-436c-911c-7073b4befd00"),
                            Price = 193m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d46ebb60-e247-4ba7-82d4-80dfc8ceee20"),
                            Count = 1,
                            HotelId = new Guid("3a736cd3-b233-436c-911c-7073b4befd00"),
                            Price = 182m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("fde0204e-166a-4435-b712-ac455dd96f91"),
                            Count = 1,
                            HotelId = new Guid("3a736cd3-b233-436c-911c-7073b4befd00"),
                            Price = 238m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("8caa4e44-79e7-4d70-ae42-263751bbcef0"),
                            Count = 3,
                            HotelId = new Guid("3a736cd3-b233-436c-911c-7073b4befd00"),
                            Price = 70m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("03c1046b-c4a7-4333-a68b-0d9ce3582f0b"),
                            Count = 3,
                            HotelId = new Guid("d7426795-c33a-4a80-887b-5fdb61e85189"),
                            Price = 219m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("3685b94e-55f9-4448-a9b0-ab93672bb874"),
                            Count = 3,
                            HotelId = new Guid("d7426795-c33a-4a80-887b-5fdb61e85189"),
                            Price = 109m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8447414d-da90-4508-b590-ddb3d6f02871"),
                            Count = 3,
                            HotelId = new Guid("d7426795-c33a-4a80-887b-5fdb61e85189"),
                            Price = 78m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("56570a72-6108-4855-b9a6-11df8fc801fa"),
                            Count = 2,
                            HotelId = new Guid("d7426795-c33a-4a80-887b-5fdb61e85189"),
                            Price = 143m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6e2a8aaa-c00d-4bb6-a127-5493d559872d"),
                            Count = 3,
                            HotelId = new Guid("5a9fa78e-b2d1-4cde-955c-1571b9a626f4"),
                            Price = 104m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("87e02661-02f8-437e-a95b-0d4bcb1a8cbd"),
                            Count = 1,
                            HotelId = new Guid("5a9fa78e-b2d1-4cde-955c-1571b9a626f4"),
                            Price = 136m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b1aba2bb-b91d-4d70-9958-f4c70a4464f6"),
                            Count = 3,
                            HotelId = new Guid("5a9fa78e-b2d1-4cde-955c-1571b9a626f4"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7c143c1f-b884-4eb3-987f-0a2b016e541b"),
                            Count = 2,
                            HotelId = new Guid("5a9fa78e-b2d1-4cde-955c-1571b9a626f4"),
                            Price = 105m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e8442234-2d5c-40df-9451-56af99d6e7be"),
                            Count = 2,
                            HotelId = new Guid("57a2fb51-16c7-4473-9eb9-f74be1117c10"),
                            Price = 211m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("42b6be9f-5e94-4574-9326-799b2c10b79c"),
                            Count = 1,
                            HotelId = new Guid("57a2fb51-16c7-4473-9eb9-f74be1117c10"),
                            Price = 77m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6a7a0995-04a0-45f3-a3a2-509bb57e0a70"),
                            Count = 2,
                            HotelId = new Guid("57a2fb51-16c7-4473-9eb9-f74be1117c10"),
                            Price = 169m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("ef75b7df-bdeb-4b20-a34b-61462023d5bb"),
                            Count = 1,
                            HotelId = new Guid("57a2fb51-16c7-4473-9eb9-f74be1117c10"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("25546242-bcef-4f76-b1d4-136ee9c38bea"),
                            Count = 2,
                            HotelId = new Guid("a6150683-f3f8-4578-ae91-74a2816b8f1c"),
                            Price = 239m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2dbdc278-8122-4eae-8934-563fd5475ea8"),
                            Count = 3,
                            HotelId = new Guid("a6150683-f3f8-4578-ae91-74a2816b8f1c"),
                            Price = 208m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2ab979ec-0134-495c-b57b-3007aaf244ce"),
                            Count = 3,
                            HotelId = new Guid("a6150683-f3f8-4578-ae91-74a2816b8f1c"),
                            Price = 161m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d9dde1db-dc1e-4379-9804-ae1d518a5a00"),
                            Count = 1,
                            HotelId = new Guid("a6150683-f3f8-4578-ae91-74a2816b8f1c"),
                            Price = 64m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9d491578-be3a-458b-bb82-bae610a0b52d"),
                            Count = 1,
                            HotelId = new Guid("1d2d61f2-2cbb-459c-be2d-1f8ed260a82f"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("171cd3d5-5028-4588-8390-de1b1d6b5b70"),
                            Count = 2,
                            HotelId = new Guid("1d2d61f2-2cbb-459c-be2d-1f8ed260a82f"),
                            Price = 234m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c1ad1055-419e-47e6-aeaa-63c1f78d430e"),
                            Count = 3,
                            HotelId = new Guid("1d2d61f2-2cbb-459c-be2d-1f8ed260a82f"),
                            Price = 84m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("30436ac7-c69e-4f9d-bf62-552b989e6d88"),
                            Count = 3,
                            HotelId = new Guid("1d2d61f2-2cbb-459c-be2d-1f8ed260a82f"),
                            Price = 216m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("efddbe45-c4c6-42f1-b849-61732723463b"),
                            Count = 2,
                            HotelId = new Guid("9534c589-acd0-49e8-bb4e-449e58445b2e"),
                            Price = 165m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9b50e494-c1e9-4240-ac65-a6ac698b6990"),
                            Count = 2,
                            HotelId = new Guid("9534c589-acd0-49e8-bb4e-449e58445b2e"),
                            Price = 88m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a5800805-229f-4d41-9032-21388f55f307"),
                            Count = 1,
                            HotelId = new Guid("9534c589-acd0-49e8-bb4e-449e58445b2e"),
                            Price = 210m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("215e4c29-e65c-44b2-832c-aba1c2a848e0"),
                            Count = 1,
                            HotelId = new Guid("9534c589-acd0-49e8-bb4e-449e58445b2e"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4b845036-57b8-4331-8c92-9f54234b0b65"),
                            Count = 1,
                            HotelId = new Guid("35f98b61-1d9e-4a7a-b9b3-1c8b88372c9b"),
                            Price = 130m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8c9ef855-4da3-4a0b-83c5-ebdbf9e1f578"),
                            Count = 3,
                            HotelId = new Guid("35f98b61-1d9e-4a7a-b9b3-1c8b88372c9b"),
                            Price = 97m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("23a2fd68-35f2-470a-9e23-a2c5d9a2b00e"),
                            Count = 3,
                            HotelId = new Guid("35f98b61-1d9e-4a7a-b9b3-1c8b88372c9b"),
                            Price = 165m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("8a57bda3-9a80-4113-b804-6c087e1c3561"),
                            Count = 1,
                            HotelId = new Guid("35f98b61-1d9e-4a7a-b9b3-1c8b88372c9b"),
                            Price = 72m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6d48d200-92ef-4035-b82f-f4c0bad8c4e1"),
                            Count = 1,
                            HotelId = new Guid("2b78b471-830c-4962-9528-1138ea6bbcd8"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("34fa625d-fa66-4455-b772-c6d78a919cf9"),
                            Count = 2,
                            HotelId = new Guid("2b78b471-830c-4962-9528-1138ea6bbcd8"),
                            Price = 125m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("47bf865a-c7ea-4cc1-b792-c4de3f342f58"),
                            Count = 1,
                            HotelId = new Guid("2b78b471-830c-4962-9528-1138ea6bbcd8"),
                            Price = 183m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("75c0a25b-3ade-4d9f-ab6e-5593fc921a5d"),
                            Count = 1,
                            HotelId = new Guid("2b78b471-830c-4962-9528-1138ea6bbcd8"),
                            Price = 84m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("20c78981-4345-4380-ad8b-e8a55b680ef9"),
                            Count = 2,
                            HotelId = new Guid("4eb84047-b94a-469c-8f86-88592dab054e"),
                            Price = 207m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("d41d9cf8-c7e5-4f49-9bd8-446062b538be"),
                            Count = 3,
                            HotelId = new Guid("4eb84047-b94a-469c-8f86-88592dab054e"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c988edc5-d871-45da-b5ad-fbfbc7624e45"),
                            Count = 3,
                            HotelId = new Guid("4eb84047-b94a-469c-8f86-88592dab054e"),
                            Price = 146m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("637b2ca5-766f-4aa2-a6cf-d10c02da1dc2"),
                            Count = 1,
                            HotelId = new Guid("4eb84047-b94a-469c-8f86-88592dab054e"),
                            Price = 119m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4641c224-a218-4202-a81c-45902ea2c2f4"),
                            Count = 3,
                            HotelId = new Guid("0737c9f6-d5d2-4670-b36a-676cf05162e7"),
                            Price = 132m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("67c98dc3-ae55-4f82-8836-55b7241f134d"),
                            Count = 2,
                            HotelId = new Guid("0737c9f6-d5d2-4670-b36a-676cf05162e7"),
                            Price = 244m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("663ca017-cba9-46cb-85e3-da0debd9f7e6"),
                            Count = 1,
                            HotelId = new Guid("0737c9f6-d5d2-4670-b36a-676cf05162e7"),
                            Price = 243m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e7d0ff6c-d840-414f-b66a-b37ff9d570ef"),
                            Count = 2,
                            HotelId = new Guid("0737c9f6-d5d2-4670-b36a-676cf05162e7"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("cc5683fb-2b91-4d3b-9526-b4603586cbac"),
                            Count = 3,
                            HotelId = new Guid("60c22255-ba18-41dd-a0ef-87dd77035055"),
                            Price = 148m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("8693e51a-0ff1-4340-998f-cfedee14e492"),
                            Count = 2,
                            HotelId = new Guid("60c22255-ba18-41dd-a0ef-87dd77035055"),
                            Price = 168m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4eb436f6-04f2-4ac0-9605-d5ce0a85b6f1"),
                            Count = 3,
                            HotelId = new Guid("60c22255-ba18-41dd-a0ef-87dd77035055"),
                            Price = 230m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9ed6436e-a00a-43c5-90e4-a83cefcb096f"),
                            Count = 3,
                            HotelId = new Guid("60c22255-ba18-41dd-a0ef-87dd77035055"),
                            Price = 111m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("8b28aaba-ec8a-4a1c-b7f3-520aa6e47202"),
                            Count = 1,
                            HotelId = new Guid("5522d316-af4b-43ab-8700-3dd77a1dc2be"),
                            Price = 201m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("fb9afd0f-826b-423e-a661-615a946ce3f9"),
                            Count = 2,
                            HotelId = new Guid("5522d316-af4b-43ab-8700-3dd77a1dc2be"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("223f3062-8c8a-4c5d-ab2f-f87cf6ea9203"),
                            Count = 2,
                            HotelId = new Guid("5522d316-af4b-43ab-8700-3dd77a1dc2be"),
                            Price = 76m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("7679c208-b47a-4eba-a904-496c6cc24171"),
                            Count = 1,
                            HotelId = new Guid("5522d316-af4b-43ab-8700-3dd77a1dc2be"),
                            Price = 63m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("69b48915-65a3-4197-8f0a-43d57ab42479"),
                            Count = 1,
                            HotelId = new Guid("ef28f7ba-5f04-49a7-aa7d-846c79471671"),
                            Price = 175m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("9851efb4-5150-4f4b-b067-794ecfef8329"),
                            Count = 1,
                            HotelId = new Guid("ef28f7ba-5f04-49a7-aa7d-846c79471671"),
                            Price = 245m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("2db45f23-e2f2-4618-b474-3f048cf2fde6"),
                            Count = 1,
                            HotelId = new Guid("ef28f7ba-5f04-49a7-aa7d-846c79471671"),
                            Price = 50m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("90c14f49-06bd-499c-af46-40be3ba789b5"),
                            Count = 1,
                            HotelId = new Guid("ef28f7ba-5f04-49a7-aa7d-846c79471671"),
                            Price = 219m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("499c017f-44ea-493b-a1bc-74cc44302b31"),
                            Count = 3,
                            HotelId = new Guid("60a51295-7af8-47ec-8a4e-4f6c4feeb74c"),
                            Price = 215m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("40fdc8fe-6269-4a29-abc7-cb4520b9bd44"),
                            Count = 1,
                            HotelId = new Guid("60a51295-7af8-47ec-8a4e-4f6c4feeb74c"),
                            Price = 164m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("98ed6096-48e6-4da7-98e9-f9c8036ce96c"),
                            Count = 3,
                            HotelId = new Guid("60a51295-7af8-47ec-8a4e-4f6c4feeb74c"),
                            Price = 163m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("f2ba77a4-7ad5-427a-b8f4-c07f88bce1c0"),
                            Count = 2,
                            HotelId = new Guid("60a51295-7af8-47ec-8a4e-4f6c4feeb74c"),
                            Price = 247m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("3471bf13-6eb0-40f4-96f0-fede47254cf7"),
                            Count = 1,
                            HotelId = new Guid("22700625-15d0-4773-8024-09759cbd76f4"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f429e78a-dd3a-4cbd-8422-85fe2cf3a805"),
                            Count = 3,
                            HotelId = new Guid("22700625-15d0-4773-8024-09759cbd76f4"),
                            Price = 149m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("885fa813-648e-4ffa-84b1-3c788945de1c"),
                            Count = 3,
                            HotelId = new Guid("22700625-15d0-4773-8024-09759cbd76f4"),
                            Price = 197m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("956ac331-8ae7-4a06-acaf-e5b1fce8dce1"),
                            Count = 2,
                            HotelId = new Guid("22700625-15d0-4773-8024-09759cbd76f4"),
                            Price = 237m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e86817b5-335d-4b80-8cc6-a8080c6b3b47"),
                            Count = 2,
                            HotelId = new Guid("b23a15ff-7161-4d3f-9da5-ddc10d69690e"),
                            Price = 87m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("2de6c432-dddd-47c4-950f-e98f909128a8"),
                            Count = 1,
                            HotelId = new Guid("b23a15ff-7161-4d3f-9da5-ddc10d69690e"),
                            Price = 247m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("8653a808-a4e6-4b33-8bdc-69ab8ea0fe82"),
                            Count = 3,
                            HotelId = new Guid("b23a15ff-7161-4d3f-9da5-ddc10d69690e"),
                            Price = 70m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("41550545-def9-4097-b614-711fd548e24e"),
                            Count = 3,
                            HotelId = new Guid("b23a15ff-7161-4d3f-9da5-ddc10d69690e"),
                            Price = 184m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("435dbf5b-4874-47e8-9092-7d046fd05a6e"),
                            Count = 3,
                            HotelId = new Guid("ac76333f-1a54-4bc7-a615-04121417b975"),
                            Price = 242m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ed787cad-94ea-401a-9522-b29727c661d5"),
                            Count = 1,
                            HotelId = new Guid("ac76333f-1a54-4bc7-a615-04121417b975"),
                            Price = 132m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("b4b784a6-bb76-407b-9e1d-3c41f95f9c67"),
                            Count = 3,
                            HotelId = new Guid("ac76333f-1a54-4bc7-a615-04121417b975"),
                            Price = 142m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("58c60bd5-99b3-4ef9-a718-b06352efa814"),
                            Count = 2,
                            HotelId = new Guid("ac76333f-1a54-4bc7-a615-04121417b975"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("8526409d-62b1-48b5-b960-6ac1e206f894"),
                            Count = 3,
                            HotelId = new Guid("b28b03ba-9bc3-4e76-aa25-8842d9da7125"),
                            Price = 233m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("872ff097-f4c8-4399-94d3-507ece35cb80"),
                            Count = 3,
                            HotelId = new Guid("b28b03ba-9bc3-4e76-aa25-8842d9da7125"),
                            Price = 204m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("49e085db-6784-421e-b6a8-5541654c0fb4"),
                            Count = 1,
                            HotelId = new Guid("b28b03ba-9bc3-4e76-aa25-8842d9da7125"),
                            Price = 171m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("34860c18-bbea-44b5-9e9f-11a6896f56cf"),
                            Count = 1,
                            HotelId = new Guid("b28b03ba-9bc3-4e76-aa25-8842d9da7125"),
                            Price = 94m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("4918879c-1374-4359-b29b-1c2e5bfeeeac"),
                            Count = 1,
                            HotelId = new Guid("a9463ad4-4c8e-4169-ac7d-888e4da65cdf"),
                            Price = 53m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f4f10e02-6c0d-4ea3-882a-bb035537660f"),
                            Count = 3,
                            HotelId = new Guid("a9463ad4-4c8e-4169-ac7d-888e4da65cdf"),
                            Price = 92m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d6365c48-d07f-4708-8f61-f8d3c7753dee"),
                            Count = 3,
                            HotelId = new Guid("a9463ad4-4c8e-4169-ac7d-888e4da65cdf"),
                            Price = 250m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("52bd9b0b-c514-441b-9406-a5bafbe54d3f"),
                            Count = 3,
                            HotelId = new Guid("a9463ad4-4c8e-4169-ac7d-888e4da65cdf"),
                            Price = 241m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("0fc548fa-0d14-47ac-bd24-90cc8b4fdc39"),
                            Count = 3,
                            HotelId = new Guid("2b0499aa-f505-4f07-96db-1beac88a40a5"),
                            Price = 190m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("58a67ae8-4a19-4fbd-a863-fcda359a968f"),
                            Count = 1,
                            HotelId = new Guid("2b0499aa-f505-4f07-96db-1beac88a40a5"),
                            Price = 112m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("869cf108-f0cf-4dc8-a6a3-759284b4eee7"),
                            Count = 2,
                            HotelId = new Guid("2b0499aa-f505-4f07-96db-1beac88a40a5"),
                            Price = 152m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("26aa3764-3c2f-403d-8bfd-323442a04c11"),
                            Count = 1,
                            HotelId = new Guid("2b0499aa-f505-4f07-96db-1beac88a40a5"),
                            Price = 177m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("6c5ca85f-1665-4dd8-b9e6-00ffba9344c9"),
                            Count = 2,
                            HotelId = new Guid("73950b5b-00a3-462b-8fe8-1ab5975538d4"),
                            Price = 60m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("94f0a3ef-6516-4a99-816a-8abd6cebad72"),
                            Count = 3,
                            HotelId = new Guid("73950b5b-00a3-462b-8fe8-1ab5975538d4"),
                            Price = 190m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1a2d8b42-107b-46b9-acea-9342ad717be3"),
                            Count = 3,
                            HotelId = new Guid("73950b5b-00a3-462b-8fe8-1ab5975538d4"),
                            Price = 77m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("4de97032-9f5f-41f5-aba0-27bd49f833ca"),
                            Count = 3,
                            HotelId = new Guid("73950b5b-00a3-462b-8fe8-1ab5975538d4"),
                            Price = 217m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("def185c7-d9a5-4dc0-8fe9-f422a1f6958a"),
                            Count = 1,
                            HotelId = new Guid("fef1b7d4-5330-46d9-9497-6c8192fb731c"),
                            Price = 146m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("271a91a6-d352-4134-8165-b2eaa8bf5dd1"),
                            Count = 3,
                            HotelId = new Guid("fef1b7d4-5330-46d9-9497-6c8192fb731c"),
                            Price = 107m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a39b32c9-bb57-4c68-af49-2fe17ecbda54"),
                            Count = 1,
                            HotelId = new Guid("fef1b7d4-5330-46d9-9497-6c8192fb731c"),
                            Price = 164m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c4d1d348-4088-4a25-bb38-214ae39bc532"),
                            Count = 3,
                            HotelId = new Guid("fef1b7d4-5330-46d9-9497-6c8192fb731c"),
                            Price = 162m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("98edaacd-b5be-450a-a7fe-b28ddd7d0dee"),
                            Count = 2,
                            HotelId = new Guid("f6721867-bada-4412-a649-efe2fea10ba8"),
                            Price = 213m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("c7539016-44bb-4297-b531-3b33d9083e49"),
                            Count = 2,
                            HotelId = new Guid("f6721867-bada-4412-a649-efe2fea10ba8"),
                            Price = 131m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("61b078c5-c99f-4ecf-99d9-39f0a30e0b2e"),
                            Count = 2,
                            HotelId = new Guid("f6721867-bada-4412-a649-efe2fea10ba8"),
                            Price = 140m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("fe1abfc2-eb08-4ed2-9c30-9c532e68df1f"),
                            Count = 2,
                            HotelId = new Guid("f6721867-bada-4412-a649-efe2fea10ba8"),
                            Price = 250m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e70a06ea-fb44-43a1-a702-ef9d085fa99a"),
                            Count = 3,
                            HotelId = new Guid("240c7544-7f24-46db-9cf4-b3a7077f3219"),
                            Price = 178m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("a9432440-21a1-4734-891d-d2b46fae7978"),
                            Count = 3,
                            HotelId = new Guid("240c7544-7f24-46db-9cf4-b3a7077f3219"),
                            Price = 216m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("ba32740b-b6c0-4956-a8f7-e282b753bc49"),
                            Count = 1,
                            HotelId = new Guid("240c7544-7f24-46db-9cf4-b3a7077f3219"),
                            Price = 98m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("10a47ce0-8164-4c86-bd0b-c76fc8a8ff7c"),
                            Count = 3,
                            HotelId = new Guid("240c7544-7f24-46db-9cf4-b3a7077f3219"),
                            Price = 165m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("e35894f2-9a28-4b41-8082-0f7d3cd6a528"),
                            Count = 3,
                            HotelId = new Guid("7df7ce44-24e8-4cba-9848-5f872b24c0e0"),
                            Price = 118m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("334cf008-6caf-4055-9a64-bc1aea9b3cc9"),
                            Count = 2,
                            HotelId = new Guid("7df7ce44-24e8-4cba-9848-5f872b24c0e0"),
                            Price = 73m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("a11e45cc-6925-4a06-b677-1caaceaba251"),
                            Count = 1,
                            HotelId = new Guid("7df7ce44-24e8-4cba-9848-5f872b24c0e0"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("fa5472ae-a0e9-4e50-b672-1918a1193fc5"),
                            Count = 2,
                            HotelId = new Guid("7df7ce44-24e8-4cba-9848-5f872b24c0e0"),
                            Price = 81m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("beac2b04-a116-421a-aac7-cef5b0e108d4"),
                            Count = 2,
                            HotelId = new Guid("df03a41e-617c-4637-be81-426f59520ff2"),
                            Price = 111m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("25297678-aec2-4580-9b2c-278edc7aa72e"),
                            Count = 1,
                            HotelId = new Guid("df03a41e-617c-4637-be81-426f59520ff2"),
                            Price = 110m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("6075777b-b85c-4797-9125-968215b7275a"),
                            Count = 1,
                            HotelId = new Guid("df03a41e-617c-4637-be81-426f59520ff2"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b22b7581-6085-41e8-ba14-a91592c86640"),
                            Count = 3,
                            HotelId = new Guid("df03a41e-617c-4637-be81-426f59520ff2"),
                            Price = 239m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ed7aaae0-c1c9-488d-b4ec-e76f0f18818d"),
                            Count = 1,
                            HotelId = new Guid("feed0ab7-f131-4481-91e0-60dba2702c8c"),
                            Price = 121m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("67064173-cba0-4c85-a727-e27f861cb424"),
                            Count = 1,
                            HotelId = new Guid("feed0ab7-f131-4481-91e0-60dba2702c8c"),
                            Price = 187m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("f0f35bc0-3e4b-48c9-8257-487d6486a78e"),
                            Count = 2,
                            HotelId = new Guid("feed0ab7-f131-4481-91e0-60dba2702c8c"),
                            Price = 201m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("5d5cd80a-04fb-4218-832f-b008af6b95a2"),
                            Count = 1,
                            HotelId = new Guid("feed0ab7-f131-4481-91e0-60dba2702c8c"),
                            Price = 73m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("ed8e4f99-4595-4d45-9646-391eb43abeb2"),
                            Count = 3,
                            HotelId = new Guid("14d17a0c-0430-4566-871f-892896a088bb"),
                            Price = 84m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("cf98de02-39d6-49f4-ae49-7457ab97d9f0"),
                            Count = 1,
                            HotelId = new Guid("14d17a0c-0430-4566-871f-892896a088bb"),
                            Price = 145m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c9a7ff67-a018-45b1-bb13-d1eda3f0ac8e"),
                            Count = 2,
                            HotelId = new Guid("14d17a0c-0430-4566-871f-892896a088bb"),
                            Price = 221m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9c101a0e-b6d9-4c41-b75e-f668662b13c0"),
                            Count = 2,
                            HotelId = new Guid("14d17a0c-0430-4566-871f-892896a088bb"),
                            Price = 108m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("9a1ae371-e120-4e51-9cbd-107ee12817b1"),
                            Count = 2,
                            HotelId = new Guid("e742c5b7-6cfd-4e8b-b50f-2df1ce562ab3"),
                            Price = 220m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("be3a41cd-acb6-4bbe-8395-752023d55dff"),
                            Count = 2,
                            HotelId = new Guid("e742c5b7-6cfd-4e8b-b50f-2df1ce562ab3"),
                            Price = 96m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("7b6463f9-eb50-42a8-af7d-198f126f7995"),
                            Count = 1,
                            HotelId = new Guid("e742c5b7-6cfd-4e8b-b50f-2df1ce562ab3"),
                            Price = 143m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("09ea0159-0ba9-41be-a4eb-908834237b5f"),
                            Count = 3,
                            HotelId = new Guid("e742c5b7-6cfd-4e8b-b50f-2df1ce562ab3"),
                            Price = 71m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("1674db33-b5e7-411d-ac84-91402146a708"),
                            Count = 2,
                            HotelId = new Guid("a34b791f-8993-4377-9177-0cd9a93330b9"),
                            Price = 179m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ee7cdeff-c704-4fd3-a770-33624add2651"),
                            Count = 3,
                            HotelId = new Guid("a34b791f-8993-4377-9177-0cd9a93330b9"),
                            Price = 155m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("bc86d357-1f1c-4234-a3cf-d7cc6fa6efde"),
                            Count = 1,
                            HotelId = new Guid("a34b791f-8993-4377-9177-0cd9a93330b9"),
                            Price = 177m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("95475da6-eaaf-4173-9ef0-6c23b7a9a6d5"),
                            Count = 1,
                            HotelId = new Guid("a34b791f-8993-4377-9177-0cd9a93330b9"),
                            Price = 195m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("28c70d81-ee90-4114-92d1-8b7016156bff"),
                            Count = 2,
                            HotelId = new Guid("f18ad2a3-87ab-4563-8a4e-62501a24ba63"),
                            Price = 76m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("4ae2d702-665d-4347-92d3-5813984799df"),
                            Count = 3,
                            HotelId = new Guid("f18ad2a3-87ab-4563-8a4e-62501a24ba63"),
                            Price = 195m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("4d762bbc-315b-47d1-a10b-f1a3f5175c83"),
                            Count = 3,
                            HotelId = new Guid("f18ad2a3-87ab-4563-8a4e-62501a24ba63"),
                            Price = 180m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("c5420e14-e7f9-4acb-98d2-6cadd0aedafa"),
                            Count = 3,
                            HotelId = new Guid("f18ad2a3-87ab-4563-8a4e-62501a24ba63"),
                            Price = 210m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("360bdfbd-6a89-44d1-bd49-68e07ed9a627"),
                            Count = 2,
                            HotelId = new Guid("df518aaf-3e1e-40cb-b5e9-d40da5debb0a"),
                            Price = 153m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("507a9201-9f1b-44fd-9367-1b65dc680cf7"),
                            Count = 2,
                            HotelId = new Guid("df518aaf-3e1e-40cb-b5e9-d40da5debb0a"),
                            Price = 221m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("1ec727a7-c4f0-4ce8-a8fb-5af444436dfa"),
                            Count = 3,
                            HotelId = new Guid("df518aaf-3e1e-40cb-b5e9-d40da5debb0a"),
                            Price = 223m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("d88630cd-6948-4dea-a29e-254a7414f8ce"),
                            Count = 3,
                            HotelId = new Guid("df518aaf-3e1e-40cb-b5e9-d40da5debb0a"),
                            Price = 135m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("f0c0a87a-718e-4790-970d-9c79b03f6dfa"),
                            Count = 2,
                            HotelId = new Guid("8df68a40-c7a2-4d3b-9956-1a7c4fcf5be3"),
                            Price = 66m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("23b9ba7e-4ba8-42c8-9257-03390125d5f5"),
                            Count = 2,
                            HotelId = new Guid("8df68a40-c7a2-4d3b-9956-1a7c4fcf5be3"),
                            Price = 179m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("df75780f-5218-4226-9024-a281f25179bb"),
                            Count = 2,
                            HotelId = new Guid("8df68a40-c7a2-4d3b-9956-1a7c4fcf5be3"),
                            Price = 125m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("1b54bbb0-be3b-456b-a1aa-aa6e84bdec0c"),
                            Count = 2,
                            HotelId = new Guid("8df68a40-c7a2-4d3b-9956-1a7c4fcf5be3"),
                            Price = 147m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("b5aabf04-e044-4d28-827d-2fd96ff9b965"),
                            Count = 2,
                            HotelId = new Guid("092ce8d5-6ec0-46ef-baa7-025b0c6a0808"),
                            Price = 176m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("1c91edd0-4e75-496e-9a1c-fb0f37a51ee8"),
                            Count = 3,
                            HotelId = new Guid("092ce8d5-6ec0-46ef-baa7-025b0c6a0808"),
                            Price = 95m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("c503db92-c734-449c-9daa-277e4880fdc9"),
                            Count = 3,
                            HotelId = new Guid("092ce8d5-6ec0-46ef-baa7-025b0c6a0808"),
                            Price = 127m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("b007c36c-60ec-4c10-a2cc-829fbe904b9e"),
                            Count = 3,
                            HotelId = new Guid("092ce8d5-6ec0-46ef-baa7-025b0c6a0808"),
                            Price = 88m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("97d6633d-74a0-4d27-b2c2-1f5462df95b5"),
                            Count = 1,
                            HotelId = new Guid("145aa16e-eeac-45bd-a513-c1ee1423e2c8"),
                            Price = 158m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("55a6248b-f118-46c1-a127-9174b922553c"),
                            Count = 2,
                            HotelId = new Guid("145aa16e-eeac-45bd-a513-c1ee1423e2c8"),
                            Price = 133m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("44cf9d74-8614-47fe-96b7-6104745b7500"),
                            Count = 3,
                            HotelId = new Guid("145aa16e-eeac-45bd-a513-c1ee1423e2c8"),
                            Price = 95m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("9aa14caf-28ae-45bd-a64f-3dca2807ef54"),
                            Count = 3,
                            HotelId = new Guid("145aa16e-eeac-45bd-a513-c1ee1423e2c8"),
                            Price = 154m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("50b04750-9b0c-4950-8828-e9225a6255da"),
                            Count = 3,
                            HotelId = new Guid("e057c1d0-789e-44ee-989c-8f393367970a"),
                            Price = 129m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("5d876c25-83d2-48f9-a486-b0d4db7a23cb"),
                            Count = 2,
                            HotelId = new Guid("e057c1d0-789e-44ee-989c-8f393367970a"),
                            Price = 62m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("663bf9a6-7fc7-45c4-9bb1-100cad5c4da0"),
                            Count = 2,
                            HotelId = new Guid("e057c1d0-789e-44ee-989c-8f393367970a"),
                            Price = 162m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e51a92bc-2897-4541-947e-ec5ca22096ea"),
                            Count = 3,
                            HotelId = new Guid("e057c1d0-789e-44ee-989c-8f393367970a"),
                            Price = 191m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("54cabb07-968e-4943-83bd-c161853d0dc7"),
                            Count = 2,
                            HotelId = new Guid("8e7d534f-b5ef-45a0-aa20-f4955f296e6b"),
                            Price = 188m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("ec30bad8-83c9-400d-a3c2-c9a66dbbb194"),
                            Count = 2,
                            HotelId = new Guid("8e7d534f-b5ef-45a0-aa20-f4955f296e6b"),
                            Price = 90m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("04ab6720-56bd-4528-98c7-6ddacb4c44e5"),
                            Count = 2,
                            HotelId = new Guid("8e7d534f-b5ef-45a0-aa20-f4955f296e6b"),
                            Price = 166m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("e41e407e-7a7f-491f-90e4-6c670599f8a6"),
                            Count = 2,
                            HotelId = new Guid("8e7d534f-b5ef-45a0-aa20-f4955f296e6b"),
                            Price = 209m,
                            Size = 5
                        },
                        new
                        {
                            Id = new Guid("7373d939-9956-4e00-94ef-ac500479612a"),
                            Count = 1,
                            HotelId = new Guid("72398cd6-f009-48f7-b6c4-0d21cc667043"),
                            Price = 123m,
                            Size = 2
                        },
                        new
                        {
                            Id = new Guid("f2246e5d-03df-42a2-909c-b370ce9c2bee"),
                            Count = 1,
                            HotelId = new Guid("72398cd6-f009-48f7-b6c4-0d21cc667043"),
                            Price = 219m,
                            Size = 3
                        },
                        new
                        {
                            Id = new Guid("d52d51ea-a24d-488a-8b1a-71951b045c35"),
                            Count = 1,
                            HotelId = new Guid("72398cd6-f009-48f7-b6c4-0d21cc667043"),
                            Price = 218m,
                            Size = 4
                        },
                        new
                        {
                            Id = new Guid("06fc3ad2-040e-4346-b59a-6367ddfb74f8"),
                            Count = 1,
                            HotelId = new Guid("72398cd6-f009-48f7-b6c4-0d21cc667043"),
                            Price = 235m,
                            Size = 5
                        });
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoomsReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomsId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("hotelservice.Models.Discount", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Discounts")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.HasOne("hotelservice.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.RoomReservation", b =>
                {
                    b.HasOne("hotelservice.Models.Room", null)
                        .WithMany("Bookings")
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("hotelservice.Models.Hotel", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("hotelservice.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
